### ISSUE TITLE
Move job retry logic into EJEA

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1117]
Depends on #1116

This is currently in the WorkflowExecutionActor but is Job-specific and probably belongs more in the EJEA.

**Comment by cjllanwarne** [comment]
(Specifically, this is the retry logic which supports the preemptible VM retries)

**Comment by Horneth** [comment]
Comment copied from the design doc. TL;DR: this sounds nice to do conceptually but is a more significant change than it looks like

> Is there a specific reason for retries to happen in the EJEA or is it because it feels cleaner ? I agree it does but it actually makes things more complicated as the retries are based on mutating the execution store which is owned by the WEA. We can change that if we don't like it, but if we don't care it will be easier/faster to let the WEA handle retries as it's already doing.

**Comment by pgrosu** [comment]
@Horneth Where is the design doc located?  It would be helpful to look at it as I infer currently everything only from source code.

Thank you,
Paul

**Comment by geoffjentry** [comment]
@pgrosu It's in our internal space, however I can give you the gist. We're doing a few things at once ...

- Make workflow submission async. Submitted workflows go into a new store and the WorkflowManagerActor can pull them as necessary. Within the store they'll be marked as either Submitted, Running or Restartable. The latter is a state which is assigned to any workflow in Running state when the system comes online
- The EngineJobExecutionActor (EJEA above) sits between the WorkflowExecutionActor and the BackendJobExecutionActor, and will manage engine-side knowledge in a persisted store. The combination of this and the above will allow us to bring back what we call the 'restart' functionality - i.e. pick up a running workflow from the engine side but not reattach to running backend jobs
- Less hashed out at the moment, if a backend will support 'recover' functionality (attaching to the backend jobs, we'll implement this in as many of our own backends as we can), the backend will need to manage its own information, e.g. using the KV store

**Comment by pgrosu** [comment]
@jeffgentry  Thank you for helping me understand better the approach.  I assume the async version of the backend is probably the [AsyncBackendJobExecutionActor.scala](https://github.com/broadinstitute/cromwell/blob/832387f34f57062abd2ce6cfa9e206407170ba72/backend/src/main/scala/cromwell/backend/async/AsyncBackendJobExecutionActor.scala) file, and some of the important stores would be the [ExecutionStore](https://github.com/broadinstitute/cromwell/blob/832387f34f57062abd2ce6cfa9e206407170ba72/core/src/main/scala/cromwell/core/ExecutionStore.scala), the [BackendJobDescriptor and BackendJobDescriptorKey](https://github.com/broadinstitute/cromwell/blob/832387f34f57062abd2ce6cfa9e206407170ba72/backend/src/main/scala/cromwell/backend/package.scala#L17-31), which contain the [Call containing the AST](https://github.com/broadinstitute/wdl4s/blob/d7e19c9f4dfbc5ad912cf641af9c640eb8a9a9c7/src/main/scala/wdl4s/Call.scala#L10-61) and sequence of [Tasks](https://github.com/broadinstitute/wdl4s/blob/d7e19c9f4dfbc5ad912cf641af9c640eb8a9a9c7/src/main/scala/wdl4s/Task.scala).

Since the WorkflowManagerActor (WMA) is just an asyncronous queue selecting the workflow based on the root and its dependencies, then it sounds to be just a scheduling pool service submitting to the EJEA, which prepares it for the specific backend.  The recovery for the EJEA is assumed to be an uniform designed protocol, which prepares the execution for the specific backend.  

Regarding the backend recovery, since at the core the implementations is really Java (even though everything is in Scala), one can save the running state periodically through serialized snapshots, using something like [Apache JavaFlow](http://commons.apache.org/sandbox/commons-javaflow/) or another similar approach.  If this becomes too cumbersome and the cost of resubmitting a job to a specific Backend is on the average time-span not excessive, then resubmitting the whole job might be Occam's razor.

There might be more approaches, depending on the preferability of flexibility, and am sure I might have miswrote something here based on my periodic analysis of the source code.

Thank you,
~p

**Comment by kcibul** [comment]
closing as per discussion in team standup.  Will revisit if we hear more need either from devs (tech debt) or customers (PO)
