### ISSUE TITLE
Calls Map during initialization is not ordered

### ISSUE THREAD

**Issue by francares** [broadinstitute/cromwell#1215]

**Comment by geoffjentry** [comment]
@francares Why do you view this as a bug? WDL explicitly states that there is no natural order outside of dependencies.

Tagging our illustrious PO @kcibul just for record keeping

**Comment by geoffjentry** [comment]
I take that back, the spec might not explicitly state this. However, that has always been the intention - the only "order" is via dependency

**Comment by francares** [comment]
@geoffjentry Current state of Reliance Point backend, that is being implemented here, requires during initialization to know the order of calls execution. This is because the component behind this backend needs to know basic execution order since it still does not understand WDL therefore it can't read a complete DAG. 
I thought this was a bug due to the loose of oder when a fold or groupBy is applied in map of call -> backend.
We have a possible release date (given by the team who is developing it) of the RP component for beginning next year which will support WDL spec but for now we need to support this.
Please let me know if we can keep this change in the engine since it does not hurt. Later when RP WDL version is in place we revert this change.

**Comment by geoffjentry** [comment]
Tagging @jainh here just so I can collapse the conversation into a single place & not both here & PR #1216 .

I'm fine w/ this since it shouldn't affect the outside behavior - technically the contract from Cromwell is that it is free to launch any runnable call at any point it wants. I do want to make sure that the "WDL order" change is never documented anywhere so that we're free to change it at any time, but IIRC #1216 doesn't do that.

**Comment by francares** [comment]
Closing this issue since we decided to not go ahead with this.
