### ISSUE TITLE
Arbitrary SgeLikeBackend command line parameters

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1217]
> We use lots of different runtime attributes (bsub job submission parameters) in our workflows.  
> 
> With existing Cromwell backends, you need to put all the possible runtime attributes in the code itself.  Would it be possible to let the user specify arbitrary runtime parameters only in the configuration file (not in the source code) that Cromwell just passes to the submit command?  
> 
> We want to avoid asking for Cromwell code changes every time we decide to use a new bsub parameter.

-- Pfizer

**Comment by ldhicks** [comment]
For any Config SFS backend, one should be able to specify optional allowed runtime attributes and their corresponding bsub/submit options within the application.conf file.  For example, within the section of application.conf to configure the backend:

```
applicationProfile = "-app"
queue = "-q"
memory = "-M"
processors = "-n"
resource = "-R"
host = "-m"
project = "-P"
```

One can then use any of the allowed runtime attributes above within a task in a WDL file or in a workflow options JSON file.  Any characters should be allowed within the outer double quotes.  In particular, escaped inner double quotes should be allowed.  For example:

```
runtime {
  applicationProfile: "large"
  queue: "idle"
  memory: "125829120"
  processors: "16,16"
  resource: "\"swp > 15 && span[hosts=1]\""
}
```
These runtime attributes will be inserted into the default bsub/submit command so that the final command line structure will be of the form:

`bsub -app large -q idle -M 125829120 -n 16,16 -R "swp > 15 && span[hosts=1]" -J ${job_name} -cwd ${cwd} -o ${out} -e ${err} ${script}`
