### ISSUE TITLE
Review 'run' command line entry points

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1260]
At the moment there's a soup of possibilities when using Cromwell in 'run' mode in terms of some files being autodetected w/ default names, the "-" syntax, optional-ness, etc. Even if we agree that this is the right combination of effects, the supporting code & documentation can be a bit confusing. For instance see the conversation on #1259 where there were multiple bits which were unclear to both myself and @mcovarr 
- As a group (interested team members, PO, perhaps input from interested users) figure out if our current scheme makes sense or if we should modify it somehow
- Make sure the code/comments are done in a straightforward manner to represent the above
- Make sure the documentation is both straightforward _and_ matches the code

**Comment by geoffjentry** [comment]
@kcibul I think this should be part of the 0.23 milestone under "wdl developer joy" angle

**Comment by pgrosu** [comment]
@geoffjentry Has https://github.com/broadinstitute/cromwell/issues/908 this already been addressed?  If so then we can have the rules defined and then documented.  The coding would come last, which make it easier to maintain without surprises

**Comment by geoffjentry** [comment]
@pgrosu Not quite, although it's one of those "it doesn't work like that anymore" things. That said, that's not what I'm talking about here. That was about runtime attributes, this is about the inputs file, options file and metadata path, and how defaults are determined - e.g. if you don't supply an inputs file it assumes it's the same path as the wdl file but with ".inputs" replacing ".wdl"

**Comment by pgrosu** [comment]
@geoffjentry Correct, I understand :)  What I am suggesting that a uniform configuration file should exist for the user (runtime attributes, file behavior, etc.):

* If a configuration does is not present, then the user is presented with an message that it will assume reading from the path of the provided files, with an example of the path.  A command "cromwell describe/get config" will show the current configuration.
* Then the program will provide them with an option like "cromwell set-config defaults" or something that makes sense for them to update the behavior to their choosing.  Then this config file will be stored/read-from a "well-known location" for looking up a user's preference.

If a program has multiple paths it can take - because of unset option - it will let the user know.  Basically the less users have to type and deal with, the more they can concentrate on getting things done :)  It will save you time in the way to update and configure new features, and it will provide user comments on preferred settings through use-cases.

**Comment by katevoss** [comment]
Part of this can be solved with better documentation, so I'll make a DSDE-docs ticket for that portion

**Comment by katevoss** [comment]
@mcovarr is this solved by your excellent refactoring of the CLI?

**Comment by mcovarr** [comment]
oh heck yeah!  😄
