### ISSUE TITLE
Refactor CC states into an EJEA subactor

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1374]
The EJEA is becoming quite the beast. It's starting to get too big to fit into a mental model so maybe we should decompose it a little.

One obvious choice might be to extract the CC output fetch and copying phases into a single state and do actual the logic in a subactor?

**Comment by geoffjentry** [comment]
One of the things I'd like to come out of the upcoming JeffDoc is identify some spots where perhaps we could take advantage of streams instead of actors. I feel like a lot of these little operations winging around the periphery would fit that model - even if at first there's not much of a need for backpressure management (but it could lead to further refactorings where it did indeed help)

**Comment by geoffjentry** [comment]
There's also a lot of crud in there that aren't directly the class. ADTs, implicit helpers, etc which could be moved out for great good

**Comment by katevoss** [comment]
@cjllanwarne What do you mean by extract the CC output fetch and copying phases? What would the affect be on Cromwell and the user? 
Do you have an idea about the effort involved to do that?

**Comment by katevoss** [comment]
Is this related to #1218 ?

**Comment by geoffjentry** [comment]
Closing this as it is nearly 2 years old.

@cjllanwarne if this is still an issue, put together a tech doc w/ a proposal
