### ISSUE TITLE
Fix polling when jobs are killed by HPC scheduler

### ISSUE THREAD

**Issue by delocalizer** [broadinstitute/cromwell#1499]
This is an issue to track the same problem that @ffinfo has raised on Gitter and PR #1346. The scenario for us is an HPC cluster environment with a scheduler (SGE or PBS) that strictly enforces walltimes; having jobs be killed by the scheduler (without producing rc file) when they exceed the requested walltime is, if not exactly common, not that rare either.

The hacky non-async solution I have been using (up until the nice configurable backends of release 0.21 changed everything in backend-land) was to have two check cycles, a frequent cheap one to see if rc existed and occasional expensive one to poll the scheduler itself: https://github.com/delocalizer/cromwell/blob/develop/engine/src/main/scala/cromwell/engine/backend/pbs/PbsBackend.scala#L128-L166

**Comment by katevoss** [comment]
@delocalizer Hi Conrad, I'm going through the backlog and came across your issue. How often are you still experiencing this problem?

**Comment by delocalizer** [comment]
@katevoss Hi Kate. I think there are two aspects to the issue worth considering - the first being how often we hit this problem in practice (I'll get back with you after I ask the production team) and the second being whether the underlying cause has been addressed - which is that relying only on the creation of a file to detect task completion is not robust at least for SGE/PBS type backends where jobs may be killed by the scheduler out-of-process without creating a file. Based only on the release changelog I suspect that the answer to the second is no. I suggest re-using the "check-alive" configuration value that's documented as currently used only on cromwell restart, for periodic (but infrequent) polling of the scheduler.

**Comment by delocalizer** [comment]
@katevoss #2281 is a dupe of this

**Comment by delocalizer** [comment]
#2315 (closed) also a dupe

**Comment by katevoss** [comment]
Good catch! I closed #2281. 

Transferring conversation here:
From @MatthewMah 
> When running jobs on backends with job runtime limits such as LSF or SLURM, jobs reaching the runtime limits are killed by the backend. [Cromwell never detects that this occurs](http://gatkforums.broadinstitute.org/wdl/discussion/9542/does-cromwell-detect-task-failures-based-on-check-alive), and will wait forever for a job that is already dead. It would be helpful to configure periodic checks for whether tasks are still alive, and enter failure modes for non-zero return codes when unfinished tasks are no longer alive. 

From @geoffjentry 
> @katevoss if I managed to correlate this correctly w/ the previous issue I was discussing w/ @kshakir it sounded like it isn't a huge deal, just that there's some nuance to it.

From @cjllanwarne:
> Some SFS backends can kill jobs outside of Cromwell, leaving us waiting forever for an rc file that will never be created.
Idea: occasionally run the check-alive command to verify that long-running jobs are indeed still alive outside of restarting Cromwell.

**Comment by katevoss** [comment]
As a **user running workflows on an HPC cluster**, I want **Cromwell to periodically check that my jobs are still running**, so that I can **know when jobs are alive versus when they reach the runtime limits and are killed by the backend**.
- Effort: **Small**
- Risk: **Small**
- Business value: **Small to Medium**

**Comment by kshakir** [comment]
> it sounded like it isn't a huge deal, just that there's some nuance to it

- Currently the mechanism for "checking if a job is done"-- in  tests and main code-- is to look for `rc` files
- On restart if the `rc` file is missing, there's a single extra check to the scheduler to see if the job is alive, by running a external command line process per job
- Thousands of jobs should NOT ping a scheduler for GridEngine/SLURM/LSF/etc. or it will be overloaded<sup>1</sup>
- It's ok to hit the filesystem [every second](https://github.com/broadinstitute/cromwell/blob/d9be2ce0993c21c209c8596f55d1295bc93d1974/supportedBackends/sfs/src/main/scala/cromwell/backend/sfs/SharedFileSystemAsyncJobExecutionActor.scala#L55) for thousands of jobs
- The current `SharedFileSystemJobExecutionActorSpec` looks for `rc` files [for up to ten seconds](https://github.com/broadinstitute/cromwell/blob/d9be2ce0993c21c209c8596f55d1295bc93d1974/backend/src/test/scala/cromwell/backend/BackendSpec.scala#L18-L20)

All this can be likely be reconciled by having the tests behave differently from the main code. Ideally, the pseduo-backend running tests should quickly test if the job is done. The "main" code could look for the `rc` files every 30s or so, and every once in a while ping the GridEngine/SLURM/LSF/etc. master to check if the job is still alive.

---

<sup>1</sup> It would also be possible to cut down on overloading the scheduler masters by batching requests, as we now do with JES/PAPI.

**Comment by MatthewMah** [comment]
@kshakir One simple possibility for batching that would work for LSF and SLURM (not sure about other schedulers) would be to query the scheduler for all user jobs that are currently running, then compare this to the expected running jobs. The output for multiple jobs is very similar to that for a single job, so parsing should not be much harder. 

- On LSF, ~~`check-alive = "bjobs ${job_id}"`~~ would be replaced by `check-alive =  "bjobs"`.
- On SLURM, ~~`check-alive = "squeue -j ${job_id}"`~~ would be replaced by `check-alive = "squeue -u ${user}"`

This scales better but would remove the ability to test for single jobs, but it sounds like this isn't used anyway.

**Comment by caross73** [comment]
We have the same issue; we use an OGE back-end that implements hard limits on resource utilization which will terminate jobs that exceed these limits without allowing them to create an rc file. Currently we are running local mode cromwell instances with a workaround of putting a time-limit on the cromwell task of 48 hours, but this is extremely wasteful of our back end resources (cromwell itself consumes a large amount of memory on our cluster nodes).

Our current workarounds involve putting a soft-limit on each job, attempting to trap SIGUSR1 in advance of the job being killed by the queue manager, at which point they create an rc file with a non-zero error code, but there is no guarantee that we can catch every instance of this. 

Ideally we would like for cromwell to query running jobs at a user configurable interval (optionally never, but not as often as the file system is pinged for rc files so as not to burden the scheduler) against its list of jobs that are both not finished, and running and at minimum trigger the equivalent error state of a non-zero rc file return code. 

We experience this problem frequently (and expect it to increase as we move more pipelines to cromwell) because our pipelines can not reliably estimate the amount of memory they need for tasks apriori.

**Comment by katevoss** [comment]
@delocalizer Any chance you still have your "hacky non-async" piece of code still? The original link you posted is no longer available, and it might be useful for @caross73. Thanks!

**Comment by delocalizer** [comment]
Er, yes that was in a fork that I appear to have deleted... :flushed:  although it wouldn't be useful as-is (was?) anymore because it was from back in the day when all the different sharedfilesystem backends were implemented in code, not defined in configuration as they are now. Last comment of @kshakir [above](https://github.com/broadinstitute/cromwell/issues/1499#issuecomment-328880929) summarizes the situation perfectly for a within-cromwell solution. If I were going to work around this now I would `cron` up a simple script that:

1. Makes API call to query the cromwell service for running jobs
2. Finds all the corresponding `stdout.submit` files in the cromwell job task call execution directories to get scheduler job ids for the cromwell job
3. Asks the scheduler for the alive-or-dead status of those scheduler job ids and if not alive, aborts the cromwell job via API call

**Comment by awacs** [comment]
Just to comment that this feature would be really useful for AWS/Cfncluster based work, since cfncluster has a known issue where compute nodes could be scaled down even with jobs still running, leaving no rc file and no way for cromwell to know that the job is already dead.

**Comment by EvanTheB** [comment]
A fix for this issue would be much appreciated! It is particularly frustrating as the check-alive config parameter sounds like exactly the test I want cromwell to run, but it is actually for different usecase.

**Comment by EvanTheB** [comment]
I thought I would be able to get a similar effect by using 
'run-in-background = true'
and (for SGE anyway) 'qsub -sync y' in my config.

Can anyone explain why that did not work?

**Comment by EvanTheB** [comment]
thanks delocalizer. I had a look in the code to make a new backend, sadly I do not know enough scala to even get started. It looks like adding a isAlive() call into the pollStatus function is all that is needed. 
SharedFileSystemAsyncJobExecutionActor.scala

**Comment by delocalizer** [comment]
Yes, but as pointed out in the summary above https://github.com/broadinstitute/cromwell/issues/1499#issuecomment-328880929, `isAlive` is a much more expensive check than looking at the filesystem and calling it at the same frequency won't scale to thousands of concurrent jobs.

**Comment by delocalizer** [comment]
FYI Our current workaround is running [this simple script](https://gist.github.com/delocalizer/6b4d97158044e1331f3c4393c9e05586) once an hour as a cron job. The details may differ slightly for SGE/SLURM/etc backends.

**Comment by cpavanrun** [comment]
I just ran into the problem of an SGE node crash that we didn't find out until we wondered why certain jobs took so long to run. Having the `is-alive` command and check run at a configurable poll interval would be really usefull for me.

Having a poll interval of 0 by default (i.e. turned off) and the value in hours/days could leave it configurable without overloading the queque masters. But as Uncle Ben said: With great power...

**Comment by Xophmeister** [comment]
I have adapted @delocalizer's script for an LSF backend: https://github.com/wtsi-hgi/olly-maersk/blob/master/zombie-killer.sh It's currently untested, but it shouldn't be far off from what's required.

**Comment by illusional** [comment]
What actually happens when `check-alive` is called?

Cromwell was accidentally terminated, while Cromwell was terminated the job finished (and an RC file with status 0 was created). When I restart Cromwell, it checks all the jobs successfully and then for the task that was running, Cromwell does the following:

1. `Restarting alignsortedbam.samtools`
2. `Assigned new job execution tokens to the following groups: cd9b05d1: 1`
3. `executing: squeue -u $(whoami)`
4. `job id: 3342271`
5. `Cromwell will watch for an rc file but will *not* double-check whether this job is actually alive (unless Cromwell restarts)`
6. `Status change from - to Running`
7. `Status change from Running to Done`
8. _Nothing_ - the next job is NOT started.

I was under the impression through the comment from @kshakir [here](https://github.com/broadinstitute/cromwell/issues/1499#issuecomment-328880929):

> - Currently the mechanism for "checking if a job is done"-- in tests and main code-- is to look for rc files
> - On restart if the rc file is missing, there's a single extra check to the scheduler to see if the job is alive, by running a external command line process per job

However, when I restart a Cromwell-39 server, it calls the `check-alive` block before it checks for the RC file. It is calling the correct `squeue -j ${jobid}` (as discussed in the [doc: Slurm config](https://cromwell.readthedocs.io/en/stable/backends/SLURM/). For reference this returns:

```
slurm_load_jobs error: Invalid job id specified
```
I tried swapping it out for `squeue -u ${user}` (and also `-u $(whoami)`) option that @MatthewMah mentioned [here](https://github.com/broadinstitute/cromwell/issues/1499#issuecomment-328984482) (just to cover my bases) which returns:

```
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
```


Cromwell doesn't seem to store the completed results, even though it successfully finds the RC file and marks the (samtools) task as Done, as when I restarted the Cromwell server (after 20 minutes), it performed exactly the same process.
