### ISSUE TITLE
SGE job number in stdout

### ISSUE THREAD

**Issue by takutosato** [broadinstitute/cromwell#1512]
Often we call a bash command in a task, read in the stdout, and set a variable to the string read in. When a cromwell job is submitted to SGE, however, cromwell prints the SGE job id to the stdout (don't know when or how often). When we then read from the stdout, the job id gets read in addition to the real output we are interested in. 

The example test wdl can be found in /humgen/gsa-hpprojects/dev/tsato/wdl/testSGE.wdl. The output of `GetBamFileName` starts with the job-id + newline character. We don't want them. The same workflow runs as expected on a GSAx server.

**Comment by delocalizer** [comment]
This looks like a bug to me too - happening because in SGE backend the stdout used by cromwell.backend.impl.sfs.config.ConfigAsyncJobExecutionActor.processArgs for job submission (where the SGE job id is written) is the same as the stdout specified to the SGE job itself in qsub. The other sfs implementation cromwell.backend.sfs.BackgroundAsyncJobExecutionActor specifies a different stdout and stderr in makeProcessRunner, suffixed with "background", so it doesn't have the same problem.

**Comment by cjllanwarne** [comment]
@kcibul this feels important enough to add to the priority lane
