### ISSUE TITLE
Adjust database settings for improved performance

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1582]
Enable batch inserts + look at changing default transaction isolation level.  Doge has more details.

**Comment by geoffjentry** [comment]
@mcovarr @kcibul Can we refine this a bit? This sounds like it could involve the `scalability` label

**Comment by geoffjentry** [comment]
I explored `rewriteBatchedStatements` as per https://github.com/slick/slick/issues/1272 as I thought this might be the magic we're supposed to ask @dvoet about. It didn't seem to have an effect but there could be some combination of operator error and our slick code confounding this. I did note that Rawls is only using this in their test `reference.conf` so perhaps this isn't what he was talking about.

I'll also note one of the last comments in that issue states that it munges the return count. I didn't look but I wouldn't be surprised if we have code checking the # of inserted entries.

**Comment by dvoet** [comment]
rawls production does use rewriteBatchedStatements=true (see https://github.com/broadinstitute/firecloud-develop/blob/prod/configs/rawls/rawls.conf.ctmpl)

You need to use it in conjunction with ```tableQuery ++= collection``` instead of ```tableQuery += item```. How are you measuring the effect? I have noticed that jProfiler will still count the inserts individually. I think the slick logs show the right thing. But this is some magic that happens inside the JDBC layer so it is hard to tell what is actually happening. I would suggest running with a local mysql with the general query log on http://dev.mysql.com/doc/refman/5.7/en/query-log.html.

**Comment by geoffjentry** [comment]
@dvoet I wondered if you all were overriding that elsewhere. Have you run into issues w/ the loss of number of inserted elements or do you all just not care about that ever?

The function in question (don't have it in front of me) was using `++=` but that's why I was wondering if perhaps there's something else about our slick code which counteracts this. My slick-fu is likely not strong enough, I'll probably need to rely on bigger guns next week. My guess is that this is the culprit.

I was looking at the general query log (I've only been using mysql, not cloudsql) and all I saw were individual inserts, never a batch insert. I can't get jprofiler to work reliably running against a JVM on GCS vms (at least not from home) so wasn't even looking at that :)

Another thought is that something upstream is actually calling our slick code per-item instead of per-collection but I don't think that's the case. It's at least something I can double check easily.

**Comment by dvoet** [comment]
Compare the mysql log with the slick log. If slick thinks it is doing batches it will be the log. Rawls is not doing anything else special.

**Comment by geoffjentry** [comment]
That's next on the list, didn't think to look at that

**Comment by geoffjentry** [comment]
I'm closing this as it will be fully contained by #1810
