### ISSUE TITLE
Overload `size` function to be able to get array size too

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1604]
So size should be:
- if given a file, determine file size as a WdlFloat
- if given an array, determine the array size as a WdlInteger

**Comment by geoffjentry** [comment]
is overloading the right thing to do here?

i think so, but as this is a DSL it's worth focus grouping to make ure it is still viewed as simple

**Comment by mcovarr** [comment]
Per @geoffjentry's suggestion, an informal poll of @jsotobroad @yfarjoun @leetl1220 @vdauwera @knoblett @katevoss (please add anyone else you feel should be involved):

The proposal is to add a version of the `size()` function that will take a single `WdlArray` argument and return its length as a `WdlInteger`.  Does this seem reasonable given the existing `size()` function that operates on `WdlFile`s (and an optional unit parameter) to return the file size?  Or can you suggest a better way to support array-length functionality in WDL?

**Comment by vdauwera** [comment]
Oy, this sounds potentially confusing since the nature of the information returned is very different. Can we just be more specific and make a new `array_size()` function? Or better yet, `array_length`?

Btw, I could see some utility in actually returning total (aggregate) file size when calling size() on an array of files... So if we make that possible, having the above be `array_length` would help disambiguate their respective purposes further.

**Comment by knoblett** [comment]
The most frequent use case I can imagine would be to iterate over all items in an array inside a `for` loop of some kind. However, I was under the impression that `for` loops weren't being implemented in WDL?

I agree with @vdauwera's suggestion on naming, provided that finding the aggregate file size of an array of files is something we want to do. If not, then extra naming distinctions would be confusing. (I can see a user trying to use `size()` rather than `array_size()`, particularly if they have previously written in a language that uses `size()` to check the length of an array. Personally, I often write things as I think they might be, and if there isn't an error thrown (i.e. `function size() does not exist`) and the behavior is not as I expect (returning a file size rather than an array length), I will spend a while trying to troubleshoot the error somewhere else, as I assume `size()` worked the way I wanted it to.

**Comment by jsotobroad** [comment]
@knoblett I would imagine you can combine a `size()` with a `range()` to scatter over the elements in a list (I think).

I don't mind the overloading but would `length()` and `size()` be simpler here?  I'm not really keen on stuff like `array_size` because then I usually go down the road of what other `X_size` exist, what do they do, and why are they special but I might just not be normal.

**Comment by vdauwera** [comment]
I like @jsotobroad's suggestion of using `length()` and `size()` to disambiguate length of a list/array/whatever vs. size of a file (or bunch of files). With that, no need to specify `X_` indeed.

**Comment by knoblett** [comment]
I would honestly have to look up what `length()` and `size()` do every time I use them because various languages use variations of those to answer the same question of "how long is my array?" For example, python uses `len()`, and c++ uses `size()`. But if the user base codes more frequently than I do, or doesn't code at all outside of WDL, then they will likely have an easier time remembering the distinction.

**Comment by vdauwera** [comment]
I find that it's always worth looking those up in any language you're not using regularly, because they're not used consistently from one to the other. And including a sanity check/test in whatever code you write, to make sure it's returning what you expect :)

**Comment by knoblett** [comment]
A good point! I'm just playing devil's advocate and trying to think from a new user's/naive non-coder's perspective, given that we advertise WDL as being easy enough for a non-programmer to use without struggling with abstractions too much.

**Comment by geoffjentry** [comment]
@knoblett That's exactly the reason we try to spread a wide net for feedback on these syntactical choices, I feel you all have the pulse of that sort of user a lot better than we do. So keep on doing what you're doing :)
