### ISSUE TITLE
Support "flattening" when copying logs and workflow outputs

### ISSUE THREAD

**Issue by ktibbett** [broadinstitute/cromwell#1641]
It would be helpful, for our production pipeline, if Cromwell's copying of workflow outputs and logs had an option to "flatten" the outputs by writing all to a single directory, instead of including the directory hierarchy when copying.  We are careful to avoid file name collisions in our output and logs so handling that case wouldn't be an issue for us -- but might for other users.

**Comment by katevoss** [comment]
@ktibbett is this still a feature that would help the production pipeline? 
@geoffjentry aside from the risk of duplicate naming for output and logs, are there any other risks involved? What would be the effort?

**Comment by geoffjentry** [comment]
@katevoss As long as we're happy providing users a bi-directional loaded gun, it's easy to do. The only difficulty here is coming up with a scheme that prevents people from overwriting their files, but KT doesn't care about that here.

**Comment by katevoss** [comment]
A bi-directional loaded gun sounds dangerous, what other ways can users shoot themselves?

**Comment by geoffjentry** [comment]
The issue is that she's asking to have everything dumped into one location. In KT's case the know all of the files will be uniquely named so that's AOK but if one enabled this feature w/o doing so and we implemented it naively one could have files being overwritten. 

This could also be implemented to have some sort of name mangling (e.g. based on original path) to ensure uniqueness, but that might not satisfy @ktibbett, she might want to make sure files retain the original name.

**Comment by katevoss** [comment]
As a **production pipeline runner**, I want **to write all output files in one directory (rather than hierarchical)**, so that I can **(@ktibbett why is this helpful?)**.
- Effort: **Small**
- Risk: **Medium**
  - if files have the same name they could be overwritten
- Business value: **TBD**

**Comment by ktibbett** [comment]
@katevoss , this is still a definite nice-to-have for us. 1642 (if not resolvable via sub-workflows) is more important.

**Comment by antonkulaga** [comment]
>The issue is that she's asking to have everything dumped into one location

In many workflows I have a task like this:
```

task copy {
    Array[File] files
    String destination

    command {
        mkdir -p ${destination}
        cp -L -R -u ${sep=' ' files} ${destination}
    }

    output {
        Array[File] out = files
    }
}
```
And I apply this task to all final outputs of my workflows because my colleagues do not want to go into super-nested folder structure with many debugging files (like logs and so on), they just want to get the final results! Having a flat-copy feature will save me from copy-pasting this task everywhere =) 

Regarding overwrite risks, I think they are exaggerated:
1) Usually, it takes you multiple runs until you get everything working, however, after that you switch to another dataset and point other members of the team to the folder they should go to pick the results from you. As I understand the copying of the workflow output happens only when the workflow succeeded.
2) The final output folder is assigned in the options. That means that for another run you can simply change it.
3) It is possible to put rewriting only if last file is newer than previous.

**Comment by dinvlad** [comment]
Is this still on the radar? Sorry for reviving an old thread.

**Comment by huangzhibo** [comment]
We have a same need.
Maybe parameter_meta in workflow can help change the  folder structure?

```
workflow foo {
  parameter_meta {
    SampleID : { description: "sample name" },
    DataInfo : {
      description: "data info: SAMPLE_ID\tFLOWCELL\tLANE\tLIB\tREAD1\tREAD2"
    }
    output_bam  : {
      ArchiveDirectory:"${SampleID}/bam/"
    },
    output_vcf  : {
      ArchiveDirectory:"${SampleID}/vcf/"
    }
  }
}
```

**Comment by kyleabeauchamp** [comment]
I too encountered this need.  The use case  is to automate the handoff of the final results to another team that does not need the full set of workflow logs and intermediates.

**Comment by oneillkza** [comment]
We're currently evaluating Cromwell for use automating some fairly large and complicated workflows, and this feature would definitely make automated handoff to downstream users easier.

@katevoss, to complete your user story:

As a production pipeline runner, I want to write all output files in one directory (rather than hierarchical), so that I can more easily and automatically locate and pass on those files to the next stage/team in the pipeline (who may not be running Cromwell).

**Comment by ruchim** [comment]
@kyleabeauchamp @antonkulaga @oneillkza @dinvlad 

How would you expect to handle collisions in the case that two workflow outputs have the same name and are being copied to the same directory?

**Comment by kyleabeauchamp** [comment]
One idea would be a "compile-time" exception by default, I suppose.  I haven't thought about this long enough to say what the right answer is.

**Comment by oneillkza** [comment]
Yeah, an exception would be a good idea in this case. It should be fairly easy to test for, and if the exception also indicated the locations of the files in execution space so they can be retrieved, that would be helpful.

In general, good user practices would be to choose a separate output directories for separate data, and to provide meaningful and unique filenames.


Note that there is a case, when re-running a workflow that failed, for intentionally overwriting the results of a previous run. It would be good to allow users to choose to do so, but probably not by default.

**Comment by dinvlad** [comment]
For our use cases, I’d say put responsibility on the pipeline developer. If there’s a collision, which file “wins” may be undefined, at least in the beginning.

In the future, It could be useful to have the status set to Failed. However, we’d like to distinguish “pipeline failure” from “output failure” in an automated way. So if it’s recognized as a Failure, then it should codify the error status to determine the cause of failure without having to parse the error message. Perhaps one could introduce FailedWithWarnings status or something better.

**Comment by rhpvorderman** [comment]
We run into the same problem with our production pipelines (i.e. not having a clean output directory structure unless we do some magic). So this would be a huge improvement to us.
@ruchim Throwing an exception and marking the job as failed would be the best. As this makes sure the pipeline developers can easily spot when there are file collisions. Cromwell exiting with an exit code other than 0 after that will also make it easier.

Another argument for having a flattened output structure: Continuous integration. We want to know if our pipeline produces certain files and these files have a certain content. However with the current output folder structure it is impossible to know where files are going to end up, so it is hard to test them.
We circumvent this by setting an "outputDir" variable in our workflows and tasks which is absolute, so the files are copied to one place. But this is less than ideal. We should not have to hack in WDL to workaround issues in the execution engine.
