### ISSUE TITLE
Email notifications on workflows

### ISSUE THREAD

**Issue by ktibbett** [broadinstitute/cromwell#1678]
Sometimes users are interested in a particular workflow and would like to know when changes to some terminal state: failure or success.  Allowing multiple users to register as interested in a workflow and emailing them when the workflow is reaches one of these states (maybe also registering the set of desired states to be notified about) would be useful.

**Comment by katevoss** [comment]
@geoffjentry I believe there was the feature from Google, pubsub, that should cover this use case. It's still on their side to finish implementing, AFAIK. Do we have an idea of how much longer it will be? Is it easier to implement pubsub or make our own solution?

**Comment by geoffjentry** [comment]
@katevoss Can you explain more? Google pubsub has been around for a while so they might be overloading words again.

**Comment by geoffjentry** [comment]
@katevoss ooooh right. I think what that is was that they'll set things up so that you can have PAPI use Google PubSub to send that notification. I don't believe that's done yet.

**Comment by Horneth** [comment]
Also that'll be to get notifications on job status not workflow. Only Cromwell knows when the workflow is done.

**Comment by katevoss** [comment]
@geoffjentry I found this in the Google Issue tracker: https://cloud.google.com/storage/docs/pubsub-notifications Would that meet our needs?

**Comment by geoffjentry** [comment]
@katevoss iirc we can't do anything with it directly (as i said, pubsub itself has been around for ages), but would need papi to be smart about it. I think there's a ticket, and sine you said you saw it in the tracker that's likely true.

also note that what @Horneth said is true. i've resisted this request for quite some time because i don't like the idea of wiring in email sending into cromwell. I wouldn't be opposed to adding a service to the service registry for workflow notifications where we provide two out of the box implementations - one which is just a Noop and one which will push a message to a pubsub topic and then users can do whatever they want with it. Similarly if a user *really* wants to have email notifications they can write their own implementation and plug it in.

**Comment by illusional** [comment]
@geoffjentry Is there a mechanism for pub/sub when running Cromwell in Server mode? We're moving to running Cromwell more as a service and less interaction-y, but we're hoping for a way that we can find out about job status changes without writing a wrapper and polling the API every 5 seconds or so.

**Comment by geoffjentry** [comment]
@illusional Not at the moment, but it's something we'd like to add in the not tooooooooo distant future

**Comment by geoffjentry** [comment]
Just saw the edit - I don't think I understand. Could you explain what you're picturing a bit more?

**Comment by illusional** [comment]
For the SFS backend (as I understand it), Cromwell looks for the presence of an `rc` file to determine whether the job has succeeded or failed. However, Slurm may terminate the job if it runs overtime or over memory and Cromwell will hang indefinitely.

I was hoping there might be a way that Slurm could notify Cromwell that the job had failed. 

Only suggestion I've got at the moment is submitting a secondary job with a `afternotok:` dependency, and if the original job fails, the secondary job will write a non-zero `rc` file into the execution directory so Cromwell knows that something has failed.

**Comment by geoffjentry** [comment]
Aha! Yeah, this is a long & heavily debated topic. Take a look at #1499 (which is old enough that it references the Gitter channel we just discussed!) - there's a lot going on in there including some workarounds but it's worth a read

**Comment by SHuang-Broad** [comment]
Upvote.

**Comment by aednichols** [comment]
The pattern in the last few years is that Cromwell focuses on being a workflow engine, and extras like email are delegated to [related services](https://terra.bio/new-in-terra-get-email-notifications-for-your-workflow-status/).

**Comment by SHuang-Broad** [comment]
Yeah, that Terra email notification is awesome.

For methods developers, we rely on our own Cromwell servers, which will benefit from this requested feature.
In addition, in Cromwell-as-an-app (Azure, AoU workbench, etc), this feature will be handy as well.

**Comment by aednichols** [comment]
It's possible that CaaA will both (1) directly expose the Cromwell API and (2) allow hooking in to Terra services such as email. 

I filed tickets for this (requires Broad login): [CaaA direct access](https://broadworkbench.atlassian.net/browse/WM-1909), [CaaA email notifs](https://broadworkbench.atlassian.net/browse/WM-1910)

Since both of those stories refer to future work in not-Cromwell, I'm going to close this issue for now and we can continue the conversation there.
