### ISSUE TITLE
Cloud SQL compatibility not tested

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1726]
There is nothing in the current Cromwell or Centaur testing protocols that checks the compatibility of our code with the Cloud SQL instances used in GOTC or FireCloud.  Currently any incompatibility issues are discovered only during acceptance testing by those customers.

**Comment by katevoss** [comment]
@mcovarr this isn't good! Is this still the case? 
@bradtaylor / @helgridly how often do you see Cloud SQL problems?

**Comment by mcovarr** [comment]
Yes I believe this is still the case.

**Comment by helgridly** [comment]
I think we had one a few months back. It's definitely been rare for us.

**Comment by katevoss** [comment]
@geoffjentry sounds like this will be necessary in a CaaS world, do you agree?

As a **FC/GOTC developer**, I want **Cromwell to test with Cloud SQL after every release**, so that I can **avoid critical (? @helgridly a bug in Cloud SQL would be critical, right?) regressions and issues in production**.
- Effort: **Medium**
- Risk: **Small**
- Business value: **Medium**

**Comment by helgridly** [comment]
Depending on the issue, a cloud SQL issue could cause anything from a failed migration and delayed release to data loss and restore from backup. (The first is extremely more likely.)

**Comment by geoffjentry** [comment]
We'll be getting this for free w/ the caas staging environment (which is in progress via @hjfbynara )

**Comment by katevoss** [comment]
In that case I'll close this and add it to the [CaaS roadmap](https://docs.google.com/document/d/1fVCsmJxiWt7Wf4f1PWJXYDy0Q45ZzgQQ5Rgo1tFzp1c/edit#heading=h.qmr433lsf04v).
