### ISSUE TITLE
Support (and docs) for SLURM

### ISSUE THREAD

**Issue by ajmazurie** [broadinstitute/cromwell#1750]
Hi guys, I was wondering if support for [SLURM](https://slurm.schedmd.com/) was on your roadmap?

**Comment by geoffjentry** [comment]
@ajmazurie It's underdocumented (where under == not at all) but you should be able to do it right now. If you look at the examples in `core/src/main/resources/reference.conf` for LSF & SGE and add a stanza like that to your own conf file but substituting the SLURM-y bits (I'm operating on the belief that it's pretty close to LSF/SGE) it should just work for you.

**Comment by antonkulaga** [comment]
Yes, docs for Slurm support will be useful.

**Comment by geoffjentry** [comment]
I came here to say what I apparently said a few months ago already :)

We don't have access to a SLURM cluster so anything we put together would be a guess on our part. I know folks have been able to pretty easily get LSF & PBS working based on our example of an SGE configuration so my assumption is that it's not hard but I have no way of knowing. If someone were to get it working and submit docs we'd happily accept them but we have no way of handling that ourselves.

**Comment by kcibul** [comment]
@ajmazurie @antonkulaga If you use SLURM, and would you be willing to write up some docs on how to use cromwell with SLURM as a contribution?  It would be appreciated!

**Comment by MatthewMah** [comment]
@geoffjentry I am currently debugging a workflow on SLURM and can provide a beta backend configuration. Should I submit this as a merge request to `core/src/main/resources/reference.conf`?

**Comment by geoffjentry** [comment]
@MatthewMah I think considering the current setup that makes the most sense. Ultimately we need a better way of handling stuff like that but such a thing doesn't exist yet. Thanks!

**Comment by katevoss** [comment]
Of the folks who have expressed in SLURM support, has anyone had a chance to try it out? Any feedback (or recommended documentation) would be great.

**Comment by geoffjentry** [comment]
We know that both @MatthewMah and Intel were able to use SLURM (albeit with different configs)

**Comment by MatthewMah** [comment]
Yes, I am using Cromwell on SLURM. The significant changes since the completed pull request for the SLURM configuration have been
1.  addition of `script-epilogue = ""` to eliminate the sync behavior after completing tasks. Sync caused some jobs to wait beyond their runtime limits for the sync to complete. 
2. `concurrent-job-limit` to limit number of jobs submitted to scheduler. The HMS staff will kill all jobs if you submit lots (many hundreds?) of jobs that complete too quickly (<1min) because this creates a bottleneck at the scheduler. `concurrent-job-limit` obviates the need to substantially rewrite the workflow, and in my case contention with other users usually limits the number of compute nodes available more than `concurrent-job-limit`. 

#1499 was a problem during pipeline development, and as a result I use very generous runtime limits for all jobs.

**Comment by geoffjentry** [comment]
There's at least one example in `cromwell.examples.conf`
