### ISSUE TITLE
Balance log messages with performance

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1807]
While playing around with some performance/scalability stuff today I saw various first hand examples just how costly logging can be in terms of throughput. 

For instance, while submitting workflows in a tight loop removing the "workflow X submitted" logging consistently improved overall requests per second (as per apache bench) by roughly 20%. This example is likely the largest offender but we should start looking at stuff like this and think carefully if the logging is worth the drain.

**Comment by katevoss** [comment]
@geoffjentry have you continued to see many logs as drowning performance? It sounds like optimizing logs could give us a large bump in scale!

**Comment by geoffjentry** [comment]
I haven't done the sort of experimentation I was doing back then since, well, then. 

IIRC there were some things which looked like they could help, I thought I had a ticket for at least one of them. 

Ah - #1809 is explicitly what I was thinking of

**Comment by katevoss** [comment]
As a **user running workflows**, I want **to see fewer unhelpful log messages**, so that **performance improves and it is easier to find important messages**.

More information and improvement ideas in the [Log spec](https://docs.google.com/document/d/1Dc37EaPDoWXacSSzLgCdndx9zo5k6EmE5tvg-2fisPo/edit#).

- effort: Small to Medium
- risk: Small
  - Currently we show too many log messages, which degrades performance. We risk showing too few, but I think it's a risk we can mitigate.
- business value: Medium 
   - Our logs are where users go to debug workflows, and currently they are a haystack to pick through.

**Comment by geoffjentry** [comment]
Closing this as logging needs to be rethought entirely anyways
