### ISSUE TITLE
Local (and presumably all SFS) can read partially written files

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#1868]
We've seen in centaur local testing that we fail at times because cromwell is reading an output file before all of its contents has been written and we have no way to detect this (except via the artificial expectation management of centaur). There was some handwaving about filesystems and putting in sleeps but both of these seem like the wrong path.

@kcibul this seems like this could go under the reliability umbrella?

**Comment by pgrosu** [comment]
@geoffjentry Maybe you write first write a file called lock or lock_specific_filename, which denotes that things are still in the process of being written.  Once all the files have been written then you just remove the lock files.  Any system trying to read will first look for the lock files.  If they are found it will wait with an exponential or constant periodic backoff, otherwise it will start reading the files.

**Comment by kcibul** [comment]
This sounds very familiar... and in that foggy memory it wasn't what we
thought it was (ie stdout still being flushed by the time we were reading
it).  Are we sure it's not a different race condition, with the same
effect?  For example, we aren't really waiting until the task is finished
before checking?



-------------------------------
Kristian Cibulskis
Engineering Director, Data Sciences & Data Engineering
Broad Institute of MIT and Harvard
kcibul@broadinstitute.org

**Comment by geoffjentry** [comment]
right, I believe this is a case where we know the end result why but have no real idea of the why why

**Comment by cjllanwarne** [comment]
Closing duplicate
