### ISSUE TITLE
Workflow stuck in running forever (900 Genomes, Workbench)

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1928]
I’ve got a workflow in the 900 genomes run that appears to be an example of Cromwell losing a job.  One of the haplotype scatters, which should take a day, instead has been going for 4 days.  JES thinks it’s done.

[This is the workflow link in FireCloud](https://portal.firecloud.org/#workspaces/engle-macarthur-ccdd%3Agenomes-reprocessing/Monitor/d2237443-0fd7-45fa-99c7-ae25ae5e3c68)

The workflow id is 9d16d8cf-7470-422d-8329-0a55a89f6411

The operation id is ELnDoOadKxj3jPfVxujN5Vwgy_-Z2IQbKg9wcm9kdWN0aW9uUXVldWU

Attached are the cromwell logs and the operations id info

[operation-metadata.txt](https://github.com/broadinstitute/cromwell/files/739430/operation-metadata.txt)
[cromwell-logs-9d16d8cf-7470-422d-8329-0a55a89f6411.txt](https://github.com/broadinstitute/cromwell/files/739431/cromwell-logs-9d16d8cf-7470-422d-8329-0a55a89f6411.txt)

**Comment by cjllanwarne** [comment]
This tight-looping of the `could not download return code file, retrying:` is typical of a problem that's been fixed in C24. 
If you see the 'never finishing' problem again in C24+, it's probably due to a different cause so please repost with new logs and metadata files (sorry!)

Closing this ticket.
