### ISSUE TITLE
File of "" in your input causes cromwell to hang

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#1954]
- 0.24
- single workflow
- local backend with docker

A file input in json of "" caused cromwell to hang.  Additionally, ``ctl-C`` just caused cromwell to hang indefinitely trying to end the workflow (that had never actually started).

**Comment by kshakir** [comment]
More info:
- Again `WdlFile` is allowing a directory to slip in, while this isn't technically supported. For another example see #1935, and others I cannot locate at the moment.
- With an input file of `""`, this directory equates to the present working directory.
- Cromwell is attempting to localize the whole directory.
- hard-link to a directory always fails, and since this is docker, soft-link isn't available.
- Cromwell is then copying everything in the pwd. Note, this includes everything under `cromwell-executions`, so it could be potentially large.
- Issuing a Control-C at this point doesn't interrupt the copy localization.

I'm not sure how we'll implement aborting copying.

**Comment by Horneth** [comment]
An empty file as workflow input will now fail the workflow. Is that ok for this ticket ?

**Comment by katevoss** [comment]
@LeeTL1220 any thoughts on this?

**Comment by LeeTL1220** [comment]
We do a lot of files of filenames and I think we'd get the same error in the case of an empty line.  Right?

**Comment by katevoss** [comment]
Since @Horneth is on vacation, @geoffjentry or @danbills care to weigh in?

**Comment by geoffjentry** [comment]
If I understand what's being asked I think so. I'm saying that more on intuition than hard evidence however

**Comment by gemmalam** [comment]
Ensure this doesn't happen on the google backend. Also, add a centaur test for local and google.
