### ISSUE TITLE
local docker permissions problems

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#2034]
I have to start cromwell with sudo to be able to run anything in docker.
In the same time when I start cromwell as sudo it creates all folders with root privileges and I have things like:
```/bin/bash: /root/bedtest/7702b69d-25ac-4d3e-964c-be15181a59c5/call-coverage/execution/script: Permission denied```
in stderr.

Here is the WDL that I run:
```
workflow bedtest {

  File first
  File second

  call coverage {
    input:first=first,second=second
  }
}

task coverage {

  File first
  File second

  command {
    bedtools coverage -sorted -a $first -b $second -counts > counts.txt
  }

  runtime {
    docker: "biocontainers/bedtools"
  }

  output {
    File counts = "counts.txt"
  }
}
```

Here are the inputs that I pass through API:
```scala
JSONObject(
    "bedtest.first" -> "/home/antonkulaga/data/assembly4/4_sorted.bam",
    "bedtest.second" -> "/home/antonkulaga/data/assembly4/9_sorted.bam"
  )
```
P.S. I also tried:
```
sudo usermod -aG docker $USER
```
that allows to run docker without sudo. The problem remains the same.

**Comment by antonkulaga** [comment]
Any thoughts on this? It is a blocker for me :(

**Comment by mcovarr** [comment]
Why do you have to run cromwell with root to be able to run anything in Docker?  Also what version of Cromwell are you using?

**Comment by mcovarr** [comment]
Ok, running the Docker daemon as root is normal (the docs says it's [required](https://docs.docker.com/engine/security/security/), actually).  The issues with non-root default users should be fixed in [this PR](https://github.com/broadinstitute/cromwell/pull/1865), but that code is currently only on develop (the forthcoming 25 release).  non-root default users should Just Work with the code from that PR, you shouldn't have to make any changes to your config.

The `master` branch corresponds to the 24 release; do you mean you're running the 23 release?

**Comment by geoffjentry** [comment]
@antonkulaga Internally we're not allowed to use docker on our unix machines for exactly this reason, so handling this problem was never prioritized by our product ownership. We had to deal with it for our work on the upcoming AWS backend, as @mcovarr pointed out. The 25 release should be out in a matter of days

**Comment by antonkulaga** [comment]
@mcovarr , the PR you are referring to is about JES, should it also fix the docker locally?
With sudo usermod -aG docker $USER I can run docker without sudo in bash but inside cromwell it did not work for some reason.

**Comment by mcovarr** [comment]
@antonkulaga that PR is for the config backend (Local, SGE, etc) and specifically *not* JES.  I see now it is a bit confusing how I worded the description in the PR... 😦

**Comment by antonkulaga** [comment]
In the latest version docker works like a charm

**Comment by geoffjentry** [comment]
Perfect, thanks for the update
