### ISSUE TITLE
Migrate Unflat Failure Metadata

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#2039]
Migrate existing failures in the metadata database from the former un-flat failure metadata style:
```
"failures": [{
    "causedBy": {
      "causedBy": {
        "message": "connect timed out"
      },
      "message": "Error getting access token for service account: "
    },
    "message": "Failed to upload authentication file"
  }]
```

to the new flat style that new workflow metadata will be created with:
```
  "failures": [{
    "message": "connect timed out"
  }, {
    "message": "Failed to upload authentication file"
  }, {
    "message": "Error getting access token for service account: "
  }]
```

Also note that aggregated exceptions were previously being input using the same random integer for every message part (i.e. every part of the aggregate was overwriting the previous one), so migration could... fix that.

**Comment by cjllanwarne** [comment]
Pinging @ansingh7115 @katevoss @abaumann for thoughts on a priority for this...

**Comment by cjllanwarne** [comment]
Oh go on, I'll ping @geoffjentry too

**Comment by abaumann** [comment]
Right now we are trying to display these failures to users in firecloud because they are currently suppressed and you can only see them if you inspect the json.  I'd prefer our UI to not show raw JSON, so we want to format the responses.  For now, we could format the known cases and show raw JSON otherwise and hope there aren't other raw JSON formats other than this.  This is definitely not a showstopper for us, but not just a nice to have, I'd say it's a P2 on a scale from P1 to P3 with P0 for showstoppers.  

We could also flatten ourselves, but there's the other case where it says "timestamp" and the singular "failure", so it's not always consistent.

**Comment by cjllanwarne** [comment]
The one consistent thing should be: there should always be a "message" element in each entry, regardless of new/old format

**Comment by helgridly** [comment]
If this is trivial-ish I would love for it to arrive in upcoming C25.

**Comment by cjllanwarne** [comment]
Oh, apart from the old failure/timestamp that doesn't seem to be used anywhere any more

**Comment by cjllanwarne** [comment]
Pinging @Horneth and @kshakir on thoughts on triviality of this. I think we'd need a query to convert everything that looks like: 
```
blah:blah:failures[123]:causedBy:causedBy:message
```
into something like:
```
blah:blah:failures[123456]:message
```

AFAIK there's not a simple SQL query that'd do that so we'd need to look more like the scala-hooky metadata migration script? How trivial was that? Also, would it take another O(migration) to complete it?

**Comment by cjllanwarne** [comment]
Oh also
```
blah:blah:failures[123]:failure
```
into 
```
blah:blah:failures[123]:message
```

And since I suspect we have collisions from aggregates, we probably want to regenerate the IDs, i.e. turning:
```
blah:blah:failures[123]:failure
```
into:
```
blah:blah:failures[456]:message
```
