### ISSUE TITLE
Keep the wdl highlighting uptodate

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/cromwell#2124]
There are several keywords that do not highlight properly (e.g. in sublime Text).

The ones I know of: The "runtime" keyword, the new if/else statements.

**Comment by geoffjentry** [comment]
The ownership of those plugins is murky at best. I don't disagree but it's not a black & white thing

**Comment by danbills** [comment]
# Re: Sublime support

## Added support for if/then/else
Runtime was already present?

## Easier Sublime Installation
In order to streamline Sublime installation, I [created a package](https://github.com/broadinstitute/wdl-sublime-syntax-highlighter) for their package manager Package Control.

## Requires moving those syntax highlighter files out of wdl repository
Sadly the package hosting mechanism requires the syntax files at the root of a repo and I didn't think the wdl repo would like that.

As soon as [this PR](https://github.com/wbond/package_control_channel/pull/6579) is merged it should be available and much easier to install from Sublime.

**Comment by danbills** [comment]
Closing this as sublime text and vim-wdl were updated.  There remains an issue w/ intellij captured [here](https://github.com/broadinstitute/winstanley/issues/10) so that remains open.
