### ISSUE TITLE
Revamp `object`

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2283]
@geoffjentry commented on [Fri May 05 2017](https://github.com/broadinstitute/wdl/issues/109)

**Needs Refinement**

We want to be able to define types for the values of objects. One suggestion was something like the following (note `struct` is using as a possible replacement for `object`, see below):

    struct MyType {
      o_f: File
      x: Array[String]
    }

    MyType foo = read_object(...)

It will coerce to the types it expects and if it can't that's a failure.

Open questions:

- Do we make a new construct (e.g. `struct` above), or replace objects
- If replace, who (if anyone) is currently using `object`
- What's the right syntax, regardless of the name of the construct. This needs focus grouping.

**Comment by patmagee** [comment]
@geoffjentry Is there an internal use case for this on your end or a community use case? I have yet to come across an instance where one of the other more concrete types will not suffice.

**Comment by geoffjentry** [comment]
@patmagee This came from @chapmanb - I don't believe we've seen any requests/use cases outside of that, but that could also just be because it's so unwieldy now that people aren't bothering at the moment. 

For history's sake, `object` was one of the tidbits that we added in the earliest days of WDL to reflect some of our personal experience with previous systems, but since they werne't really being used the whole thing became a dusty corner.

**Comment by chapmanb** [comment]
Patrick -- thanks for looking at this. I'd like to use Objects to group together related items so we can pass them as a single sample to processes. This enables things like batch or tumor/normal calling where you have multiple samples together and want to bundle each of items with each other. I've got a mock up of how I'd use it in a real somatic workflow here:

https://github.com/bcbio/test_bcbio_cwl/blob/master/somatic/somatic-wdl/main_somatic.wdl

The issue with current objects is that the items are typed so platforms can't identify files for localizing them. Happy to provide more details if it would help.

**Comment by orodeh** [comment]
I am currently experimenting with wdl4s object support in [dxWDL](https://github.com/dnanexus-rnd/dxWDL). The first use case is for representing JSON objects; it turns out that the syntax is very similar. I don't know if that is a coincidence. Presently, I am having trouble with the WDL object typing. For example, the workflow below: 

```
workflow wf_complex {
    Object z = {"a": 3, "b": 1}

    output {
        Int sum = z.a + z.b
    }
}
```
When evaluated with Cromwell
```
java -jar cromwell-29.jar run wf_complex.wdl
```
reports: 
```
 "outputs": {
    "wf_complex.sum": 31
  }
```
However, I would think `a` and `b` are integers, and the addition result should be `4`. Clearly, Cromwell thinks these are strings, and the addition concatenates `3` to `1` instead. Had `z` been a JSON object, the values would have been interpreted as integers, as intended. 

1) Can the experts shed light on the situation? 
2) How do I create a WDL object literal?

**Comment by patmagee** [comment]
@Chapman I understand your issue. I encountered the Same thing when doing multi-sample workflows a while ago (since then I have only been writing single samples). I think I got around it by using a combination or multiple arrays and typed Maps. Not necessarily ideal, especially since at the time there was no `range()` function.

For a use case like that, it seems like a `struct` type makes total sense.  I feel like `Object` is mainly useful as an internal type.

@orodeh, I'm not 100% certain and @geoffjentry can correct me if I am wrong, but I believe I read somewhere that all members in an object are interpreted as strings. Therefore what you are seeing is string concatenation first, and then a type coercion to an int. 

If you have a statically typed object, I would suggest using the `Map` type.

**Comment by orodeh** [comment]
@patmagee thanks, that clarifies this mysterious object behavior. For what it is worth, I like structs better, because they are statically typed, and are easier to program with.

**Comment by geoffjentry** [comment]
@orodeh It's definitely not a coincidence that `object` is like json objects. while we didn't have a real use case when we first designed WDL, the handwaving was that it was a json object-like thing

@chapmanb @patmagee @orodeh @katevoss @vdauwera - considering `object` as-is isn't working for anyone (and is likely implemented incorrectly in Cromwell/WDL4s anyways) and we seem to be having a moment here, this seems like a good opportunity to rethink what this construct *should* be. It doesn't seem like we're far from a consensus anyways. Any suggestions on best scheme for collaborating/brainstorming this (assuming ppl are willing) .... here on github, shared google doc, email?

**Comment by orodeh** [comment]
@geoffjentry It would be great to collaborate and come up with a good solution. In my opinion, we can continue the discussion here on github. That is my two cents.

**Comment by patmagee** [comment]
@geoffjentry Github seems like a good enough place for now! At least for the initial discussion of what the the best type of construct would be. 

It would be good to identify all of the current uses of the `Object`  type, both internally to cromwell / wdl, and externally in users workflows. Any replacement should address all of the current uses while adding the functionality we need.

**Comment by chapmanb** [comment]
Jeff, Ohad, Patrick and all;
Discussing on GitHub works great for me. From my side having equivalent functionality to CWL records (http://www.commonwl.org/v1.0/CommandLineTool.html#CommandInputRecordSchema) would be perfect for me. Essentially it's a set of typed key/value pairs, so the current objects plus typing. CWL allows nested records but having a flat structure is fine with me if that's easier for implementation and support. Happy to provide any more details that would be helpful. Thanks again for looking at this.

**Comment by geetduggal** [comment]
+1 on this :)  I think the idea of `struct` would be very useful to potentially enhance/replace the Object type.   May want the order of the type and variable name to be consistent with other WDL, e.g. instead of:

```
struct MyType {
  o_f: File
  x: Array[String]
}
```

```
struct MyType {
  File of
  Array[String] x
}
```

IMHO, the word `struct` is nice since it pays homage to C and it seems like a fairly nice correspondence.  May want to consider `tuple` as well.

Finally, I think a nice benefit of this is that it could have nice correspondence with records in CWL and thus potentially a nice representation in the WOM to handle both.

**Comment by geoffjentry** [comment]
@patmagee re use cases I wouldn't be surprised if no one internally is using `object` but I'll try to investigate

**Comment by geoffjentry** [comment]
Although now that I've said that I know that we *do* have a use case where something like this is being requested. They want a typed set of key/value pairs, but the thing that they really want is to be able to define some boundaries (e.g. "Foo" is a number between 1 and 10) and to have the static analysis fail to validate the workflow if one of these are a workflow input and the values are wrong.

Now that I type that out, having refinement types in WDL seems like a bad path to be going down. I should verify that's *really* what they want or if I read too much into an example they gave.

**Comment by patmagee** [comment]
@geoffjentry if the use case is really intended for validation criteria on objects which the user sets, I feel the same as you, that this is an abstraction that should not be handled withing wdl/cromwell. 

While I understand the use case (we also have toyed around with the idea of this as a feature request) it adds unnecessary boundaries to object types that should be handled at the level of execution and not job submition. 

I think what might be of use in these instances, for users (like myself) is using the parameter meta more efficiently to define in writing what constitutes valid  entries. 

Going back to the idea of objects as typed key Value pairs, I still think this is a valid idea, that has real use cases and purposes. In many cases data must be paired with other corresponding datasets and values.  In a scatter operation having these types of structured objects would greatly simplify how we can group data together

**Comment by aednichols** [comment]
This is in Cromwell now
