### ISSUE TITLE
Fail slow mode is (very likely) broken

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#2297]
Workflows can stay in "Running" mode forever. I will update this ticket with a WDL to reproduce it.

**Comment by kcibul** [comment]
We see this regularly when running the joint calling workflow on 11k samples.  @katevoss I think we should prioritize this one as with this bug people (ops) can't really run the workflow in production

**Comment by kcibul** [comment]
Talking with @Horneth and @cjllanwarne -- there was a thought this has to do with a gather operation on shards that fail.  That the gather task is always waiting to run, because it either expects that all shards will complete successfully OR the workflow will be terminated but because of continueWhilePossible... neither of those is the case

**Comment by ruchim** [comment]
Suspicion confirmed! There is a collector key for each scatter that is a part of the execution store in Cromwell--and it's being abandoned in the "NotStarted" state when there is a failure in the Scatter in ContinueWhilePossible mode. Because there is a "NotStarted" key in the store--the workflow remains in the "Running" state with a job that's not really an executable.
