### ISSUE TITLE
Split WDL4S into WDL and WOM subprojects

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#2308]
This is a much bigger split than separating the packages but will allow us to enforce the dependency direction:
- `wdl` depends on `wom`
- `wom` **must not** depend on `wdl`

**Comment by katevoss** [comment]
@cjllanwarne are there any more issues under this Epic? Or can this be closed?

**Comment by mcovarr** [comment]
tl;dr there's a lot more work to do here and this should not be closed.

I made subprojects for `wom`, `wdl`, and `cwl`, but in reality all the WDL stuff was dumped into `wom` rather than `wdl` where it properly belongs.  WDL and WOM are currently very entangled, and Cromwell is talking exclusively to WDL interfaces rather than the WOM interfaces it should use.

**Comment by mcovarr** [comment]
To answer your actual question: there are currently no more issues under this epic, but there should be.  🙂   Those actually working on this should decompose the remaining work into new issues as they see fit.

**Comment by katevoss** [comment]
@mcovarr and @danbills I believe you are working on remaining work 😃  if this epic is still useful then feel free to use it, but if you have other ways of grouping what you're working on, I can close this.

**Comment by mcovarr** [comment]
There should be more tickets here, I'll find them or start creating them. 😄
