### ISSUE TITLE
Allow JES to not copy files when call caching

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2330]
With the SFS backend, when call caching files can be copied, sym linked or hard linked. With JES we only support copying the file.

Provide a mechanism for the JES backend in the config file to either copy the files or leave them in place and access them that way.

**Comment by Horneth** [comment]
I feel like we should harmonize it to the point where we should also provide this option for SFS too then no ?

**Comment by cjllanwarne** [comment]
@Horneth I thought the point was that SFS does already have it... Did you mean TES?

**Comment by mcovarr** [comment]
Should we confirm the cached-to files are still where they are supposed to be and accessible?

**Comment by Horneth** [comment]
SFS does not have a "use original path" AFAIK. It has "copy", "hard-link" and "soft-link".
Those are "duplication strategies".
There are also "hashing strategies", for file, which can be "hash file content" or "hash file path". With an optional "use sibling md5 if it exists".
I guess the question is, how much of all that do we want to standardize.

**Comment by geoffjentry** [comment]
@mcovarr Yeah. If possible it'd be good to treat it as a miss I think.

@Horneth I feel like this is an implementation detail for standardized behavior. The [sym|hard]link options in SFS are in effect leaving the original file in place. There's no link concept in GCS so this is the same end effect albeit different implementation. Now the question is if you buy that argument :)

**Comment by Horneth** [comment]
Linking vs not doing anything still does have an impact regarding call caching.
For example, currently on SFS if you use the "hash the file path" strategy, then you have to use symlink in order for it to work otherwise we have no way to know the original file path and hence call caching breaks. If we provided the "don't do anything option" on SFS too it would be another way to get call caching to work with "file path hashing".
I'm just saying there is a soup of options regarding hashing and file duplication that would be nice to get as coherent as possible (even though like you said linking on GCS doesn't make sense). And I agree that all of this might very well be an implementation detail :)

**Comment by geoffjentry** [comment]
Discussed in person w/ @Horneth - we'll keep the implementation specific split for now. It seems likely that in the future it'll boil down to a cloud/not-cloud split but at the moment it's SFS/PAPI

**Comment by mcovarr** [comment]
@geoffjentry probably better to treat a cached-to 404 the same as a failed cache hit copy so we can fall back to trying another cache hit rather than re-running the job.

**Comment by geoffjentry** [comment]
Yeh that's actually what I meant so I'm glad you picked up on my bad phrasing :)

**Comment by katevoss** [comment]
@geoffjentry this is complete, right?

**Comment by geoffjentry** [comment]
yes, as of 28

**Comment by katevoss** [comment]
@geoffjentry does this mean that users can choose to link to the results rather than copy the results when they get a cache hit?
