### ISSUE TITLE
Race condition while checking stderr

### ISSUE THREAD

**Issue by danbills** [broadinstitute/cromwell#2378]
As mentioned in [this forum post](http://gatkforums.broadinstitute.org/gatk/discussion/comment/39791), there appears to be a race between cromwell checking stderr and it actually being written/flushed to disk.

> WDL seemed to fail with a file not found error always in regard to the stderr file, but when I look up the file manually the file was always there, and the specific task also finished with rc=0, but the main cromwell process failed with return code of 1 already due to the file not found error.

**Comment by katevoss** [comment]
@danbills can you explain more about when the error occurs? Do you have an idea of how much effort it would take to fix?

**Comment by danbills** [comment]
I was relaying information from the forum and am not familiar enough with the issue to describe the situation or effort to fix.  Perhaps @Horneth or @mcovarr could shed some light?

**Comment by Horneth** [comment]
This PR probably helped https://github.com/broadinstitute/cromwell/commit/90f1e17b43d27fe0ccb794ff36d367ca19a41966
by not checking stderr if we don't need to.

Increasing the number of IO retries won't change anything because we don't retry on a "FileNotFound".

I'm wondering if this is not the same thing we're seeing in travis sometimes where stdout is empty, but this time worse (the file doesn't even exist)

**Comment by katevoss** [comment]
As a **user running workflows**, I want to **see my stderr output even when Cromwell gets a "FileNotFound" response** so that I can **debug my workflow**.
- Effort: @Horneth do you have an idea of how much effort this would take to fix? 
- Risk: Small
- Business value: Small
   - There is a workaround, to manually look up the stderr

**Comment by Horneth** [comment]
@katevoss if the issue is what I think it is then I'm not sure how to fix it so I don't know how much time it would take, we've tried to fix it a few times already and failed.
Also I wouldn't say that manually looking up stderr is a workaround if Cromwell fails the workflow for an invalid reason

**Comment by katevoss** [comment]
@geoffjentry any thoughts on how to fix this issue?

**Comment by geoffjentry** [comment]
My intuition is what @Horneth said, that this is an artifact of something we've seen before. It is possible to sorta-fix-it-fix-it (e.g. write out a "i'm totally done" file at the very end and not read anything until then) but that has its own problems, including some which lead to the "sorta-" prefix there.

It's worth noting that this isn't a problem unique to Cromwell, it pops up fairly regularly with these things.

**Comment by katevoss** [comment]
In that case is it a won't-fix situation? We can keep patching if necessary.

**Comment by geoffjentry** [comment]
That's the path we've been taking. At some point if this becomes a big enough headache paying the pain to try to fix it more would be worth it but for now it's not IMO

**Comment by ruchim** [comment]
Closing it as we won't be fixing this for now. It can be re-opened by anyone who experiences this issue again in the future.
