### ISSUE TITLE
Auto release wdltool on github

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#2400]

**Comment by katevoss** [comment]
@Horneth is this issue to auto-release wdltool when we release Cromwell?

**Comment by Horneth** [comment]
yes

**Comment by katevoss** [comment]
As a **Cromwell dev**, I want **wdltool to be released automatically**, so that **when I release Cromwell, wdltool is released and up to date**.
- Effort: @Horneth how much effort would this take?
- Risk: Small
- Business Value: @Horneth how much time/effort does it take to manually release wdltool? how much risk of human error is there?

**Comment by ruchim** [comment]
I believe we auto release womtool now. @Horneth please re-open if I missed soomething.
