### ISSUE TITLE
Wait for Cromwell travis master build to go green before releasing to github

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#2401]

**Comment by katevoss** [comment]
@Horneth is this a reminder, or is there something that needs to be added or changed here?

**Comment by Horneth** [comment]
It's a release improvement ticket. Currently the release WDL creates a github release even if the build fails on the master branch right after merging

**Comment by katevoss** [comment]
related to #2399 and #2830 

As a **Cromwell dev**, I want to **automatically release Cromwell once Travis is green**, so that **Travis doesn't release when it's failing**.
- effort: small
- risk: small
- business value: small (to medium)
   - have there been any regressions that Travis would have caught but it was red when we released?

**Comment by ruchim** [comment]
I believe this has been done already: https://github.com/broadinstitute/cromwell/blob/develop/release/release_workflow.wdl#L24-L33

@Horneth please re-open if I misunderstood.
