### ISSUE TITLE
Convert to using Circe

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2423]
We seem to be gravitating towards circe in general, convert Cromwell from spray-json to circe

**Comment by katevoss** [comment]
@geoffjentry what is Circe? What effort would this take?

**Comment by geoffjentry** [comment]
https://github.com/circe/circe

it wouldn't be a huge project but it's also not a huge need. since we're using circe everywhere else now it just means we have two different ways of doing the same thing

**Comment by kshakir** [comment]
Related to switching to circe, and printing JSON in general, pretty-vs-compact printing has been up for debate.

Here is an example of how to pretty print in circe: https://github.com/broadinstitute/clio/commit/4b78f9a5d2f5a0aea389dc404859d5f91e07321c#diff-4543387a548c3521400bdaa006943757

The above always pretty-prints. It may be the case that one wants the pretty-vs-compact printing to be an [option](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html). Because this particular solution uses implicits, one _could_ turn this

```scala
implicit val akkaHttpJsonPrinter: Printer
```

into

```scala
implicit def akkaHttpJsonPrinter()(implicit cromwellPrintType: CromwellPrintType): Printer
```

and then implicitly provide an enum set by a query string parameter.
