### ISSUE TITLE
Please don't re-release files under same version

### ISSUE THREAD

**Issue by tseemann** [broadinstitute/cromwell#2480]
you recently released version "28", then found a bug, and changed the JAR download, but still called it "28".

This has caused problems for brew, conda etc who package releases and use SHA256 to verify.

It would have been better if you made it a "29" release, and delete the "28" release.

Thank you for considering this opinion.

**Comment by geoffjentry** [comment]
Hi @tseemann - 

Thanks, we're aware. We followed the instructions on brew's site and used the revision flag, but eventually worked it out with @ilovezfs to use `28.1` in this casee. We don't, at least for now, release our software to bioconda. We've since decided to switch to an x.y system as our x versions are meaningful internally and shouldn't be changing for things like critical bug fixes.
