### ISSUE TITLE
Better error reporting when a cromwell task is canceled by google due to 6 day limit

### ISSUE THREAD

**Issue by pshapiro4broad** [broadinstitute/cromwell#2496]
We have a cromwell task that failed with the unhelpful error message:  `Unexpected failure in EJEA (root cause not captured).` After investigation we found that the task was being killed by the google cloud compute system:
```
  "error": {
    "code": 1,
    "message": "Operation canceled at 2017-07-23T01:01:39-07:00 because it is older than 6 days"
  },
```
It would be better if cromwell was able to report this error directly, so we don't have to look at the gcloud operations properties.

Looking at the cromwell logs I see this sequence:
```
2017-07-23 08:09:42 [cromwell-system-akka.actor.default-dispatcher-3449] WARN  c.e.w.l.e.WorkflowExecutionActor - WorkflowExecutionActor-f15009ab-b5bc-47ac-b832-3d0ae2f15888 [UUID(f15009ab)]: WorkflowExecutionActor [UUID(f15009ab)] received an unhandled message: AbortedResponse(PairedEndSingleSampleWorkflow.MarkDuplicates:-1:1) in state: WorkflowExecutionInProgressState
2017-07-23 08:09:47 [cromwell-system-akka.actor.default-dispatcher-3375] ERROR c.e.workflow.WorkflowManagerActor - WorkflowManagerActor Workflow f15009ab-b5bc-47ac-b832-3d0ae2f15888 failed (during ExecutingWorkflowState): Unexpected failure in EJEA (root cause not captured).
```

In this case the google operations ID is `EOjNtPvUKxiOgeqc763--TEgn6KQ6Z4NKg9wcm9kdWN0aW9uUXVldWU`.

I can provide more operations IDs if necessary.

**Comment by geoffjentry** [comment]
Thanks @pshapiro4broad 

Yes, I agree that this should be fixed. That error is being caught by our "oops we have no idea what happened" when clearly there's some repeatable code path causing an error here where we *should* know what's going on. It'd be good to fix this.

**Comment by kcibul** [comment]
+1

-------------------------------
Kristian Cibulskis
Engineering Director, Data Sciences Platform
Broad Institute of MIT and Harvard
kcibul@broadinstitute.org

**Comment by ruchim** [comment]
https://gatkforums.broadinstitute.org/firecloud/discussion/11853/error-message-the-job-was-aborted-from-outside-cromwell

AC: The message "Job was aborted from outside Cromwell" itself doesn't have enough information to understand what happened, and what to do next. It seems like there are two known failures that can lead to that error message:

1. As described above, when an operation self-cancels due to a timeout, Cromwell could supplement the existing message with:
```Jobs that run for longer than a week are not yet supported, and thus this job was cancelled because it exceeded that upper-limit. Please try to reduce the duration of your job. To get more details about your jobs, here are links to the stdout/stderr files...```

2. As described in the forum post above, when Cromwell restarts a workflow and a job had been started by the engine/backend but didn't have an op id -- it gets marked as a failed job with the same error. Instead, if Cromwell knows that the reason it couldn't find an op id was because it is restarting -- then it should not report the message it does today at all and simply say:
```When Cromwell restarted, it realized the job was not yet started, and so this is a benign failure. Cromwell will try attempting to execute this job again.```
