### ISSUE TITLE
Proposal for changes to interpreting inputs (and their types)

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#2565]
I think this is what most people mean when they write declarations in WDL. Some are a bit different from how they're currently interpreted but I think it should make things easier and safer (eg. if it's an optional that has a default, don't force a `select_first`...)

## Example
```
workflow foo {
    Int a      
    Int b = 5  
    Int c = b  
    Int? d     
    Int? e = 6
    Int? f = d 
}
```

|Declaration | Type | *Must* be supplied | **Can** be supplied | Notes | 
|-------|-----------|-------|-|-|
| `Int a` | Int | Yes | Yes | |
| `Int b = 5` | Int | No | Yes | |
| `Int c = b` | Int | No | ~~Yes~~ **No** | Intermediate value. Shouldn't be overridden because it has variable references. |
| `Int? d` | Int? | No | Yes |  |
| `Int? e = 5` | ~~Int?~~ **Int** | No | Yes | Can be treated as an `Int` because it has a default |
| `Int? f = d` | Int? | No | ~~Yes~~ **No** | Intermediate value. Shouldn't be overridden because it has variable references. |

**Comment by vdauwera** [comment]
This all seems reasonable to me.

**Comment by geoffjentry** [comment]
My $0.02 is that for the two w the intermediate value note that allowing the behavior seems like a bug waiting to happen - enough so that it's worth annoying the one person out there who really really wants to do that.

For the middle change, the `Int?` treated as `Int` - I like it, but I'm a little concerned it could get confusing. Specifically Im picturing my utter confusion the first handful of times I encountered implicit conversions in scala

**Comment by vdauwera** [comment]
Actually now that I think about it more I don't understand why the two with intermediate values can't be overridden. Is it bad to provide a default value that may depend on something else? I can think of cases where that would be useful. 

The middle change is very helpful -- I'm willing to put up with a bit of potential confusion in order to have it. 

One other question: will this affect what gets listed as "requested" by `wdltool inputs`? I'd like for everything that *can* be supplied to be in there even if I provided a default value.

**Comment by geoffjentry** [comment]
@vdauwera My thought was that if you're wiring up something like that that there's probably a good reason to have done so. I could easily see people wanting to munge those values when debugging and such but then would it be an attractive nuisance once released into the wild?

**Comment by vdauwera** [comment]
Well, here's a use case. I want to run the same workflow on exomes and on whole genomes, and some of my parameters take different defaults depending on the data type. It would be swell to be able to say e.g. `my_param = param_values[data_type]` assuming I've set up my defaults as maps with e.g. 'wgs' and 'exome' as keys, and I can somewhere set `data_type = 'wgs'` (because presumably several values would need to be switched) (by the way, does wdl have enums?).

So I'd have defaults that are variable references -- but I might decide to use something else entirely and just input my_workflow.my_param = 5 in my json for whatever reason. 

Is that crazy/wrong?

I guess I could instead do the override by injecting the value I want into `param_values`...?  But then I'm constrained to work with whatever `data_types` have been planned for and can't add something different on the fly. 

Does any of this make sense?

**Comment by geoffjentry** [comment]
@vdauwera I was definitely only picturing the "input my_workflow.my_param = 5 in my json for whatever reason." example.

**Comment by yfarjoun** [comment]
I think that defaults should be allowed to be overridden, even if the default value is based on another variable. Not sure I agree with the logic to prevent that.

**Comment by geoffjentry** [comment]
@yfarjoun Yeah, I agree. @vdauwera quickly provided a totally valid use case beyond "I'm screwing around".

Specifically what I was concerned about here is providing a case where we allow corners to be cuttable for the implementer which then leave loaded guns sitting around for downstream users to shoot themselves with.

**Comment by cjllanwarne** [comment]
OK, I think we can close this, but I'll re-introduce the `Int?` with default => `Int` as a bug, since I believe that's how optional inputs **used** to work anyway
