### ISSUE TITLE
Return Labels as a part of the query response

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#2851]
Mint has an important use case for having workflow labels being returned as a part of the query response for the GET/POST `/query` endpoint. Their only other option is to call the the `/metadata` endpoint for each and every workflow being returned by the response from a call to the `/query` endpoint.

**Comment by ruchim** [comment]
@kbergin @samanehsan

**Comment by geoffjentry** [comment]
Ultimately I think the answer is being able to specify desired fields. We can't just keep glomming whatever artifact people want onto query because it'll wind up becoming as much of a mess as metadata.

**Comment by ruchim** [comment]
@geoffjentry I think that's a good suggestion and that can be an implementation detail as a part of this work, making the query response mutable, similar to how the include/exclude key's work for `/metadata`?.

**Comment by geoffjentry** [comment]
Something like that. The key is that by default query should be pretty lean and we should never get in the habit of adding random this's and that's to the basic response just because one group or another would find it convenient. 

The other direction to go (and now that I think about it I think this seems better in some ways) would be to:
a) allow for batch metadata-y type requests
b) if one can't get what they want via includeKeys provide new metadata-y endpoints to give them what they want

Then the workflow would be to query for the wfids that you want to just get the wfids which match a particular query* and then send them en masse as a batch request to get exactly the sub-info they want

* One might ask why there's non-wfid stuff in query and why did we draw the line where we did, to which I'd say "good question"

**Comment by ruchim** [comment]
Closed by https://github.com/broadinstitute/cromwell/pull/2971
