### ISSUE TITLE
Swagger uses deprecated parameter names

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#2939]
The 'wdlSource' parameter name has been deprecated in favor of 'workflowSource'.
Support for 'wdlSource' will be removed from future versions of Cromwell.
Please switch to using 'workflowSource' in future submissions.
         

The 'wdlDependencies' parameter name has been deprecated in favor of 'workflowDependencies'.
Support for 'wdlDependencies' will be removed from future versions of Cromwell.
Please switch to using 'workflowDependencies' in future submissions.

**Comment by geoffjentry** [comment]
FWIW I didn't even bother adding the old ones to CaaS

**Comment by kshakir** [comment]
There's [nothing](https://github.com/broadinstitute/cromwell/blob/5e325e98785670d2bf12bd98590a082c89e25a94/engine/src/main/resources/swagger/cromwell.yaml#L20) wrong with the swagger [yaml](https://github.com/broadinstitute/cromwell/blob/5e325e98785670d2bf12bd98590a082c89e25a94/engine/src/main/resources/swagger/cromwell.yaml#L67) in develop.

This issue is a problem in the scala code, and a dupe of #2854.

**Comment by mcovarr** [comment]
dupe and also apparently not the real problem 😦
