### ISSUE TITLE
RFE: add monitoring_script as a runtime attribute in JES

### ISSUE THREAD

**Issue by dheiman** [broadinstitute/cromwell#2990]
One of the biggest pain-points in FireCloud is the inability to see how much memory a tool used, thus making it hard to optimize memory requests. It would be awesome if `monitoring_script` could be a runtime attribute as well as a workflow option to enable memory profiling.

**Comment by geoffjentry** [comment]
No. Runtime will almost certainly be moving in the opposite direction as it already has too much Cromwell specific stuff in there

**Comment by geoffjentry** [comment]
The more appropriate suggestion here would be to work with the firecloud team to give you more direct control over your Cromwell experience

**Comment by dheiman** [comment]
Isn't the `runtime` section supposed to be backend/engine specific? Maybe this discussion belongs more in the openWDL board, but having a section that is simply defined as key-value pairs that allows expressions, the implementation of which is at least partially engine specific (as an engine may implement for multiple backends) makes a lot of sense to me. While there are plenty of key-values that are easily generalized, and can be fixed for such a section, backends almost invariably have specialized specific options that are best controlled on the fly rather than via fixed configs.

As an analogy, The DRMAA API allowed for this with SGE and similar run-execution engines, by generalizing common functions, and allowing pass-through of specific ones (e.g. soft memory limits, if my vague memory serves).

**Comment by geoffjentry** [comment]
I'd argue that the arbitrary KV thing was one of the largest mistakes from Original WDL (i.e. what came out of the 2 weeks of us locking ourselves in a room and figuring it all out) as it destroys portability unless one adds *some* structure to it. We've doubled down on it over the years by adding what IMO should be Cromwell workflow options into the runtime block which means that a WDL can now have important control information on it which might ruin the portability of that workflow. The worst example I can think of is `backend` which is a purely Cromwell concept - what happens when that workflow goes to run on DNAnexus? What happens when `backend` is *also* a concept in another engine but it means something else? What happens when one engine interprets `cpu` to mean "at least this much" and another "exactly this much"? What happens when in the former case the user gets charged more money than they thought because more memory than they needed was allocated? What happens when one engine assumes `mem` is just a number representing GB and can't parse a string w/ units?

(admittedly `mem` is a bad example as it's one of the very few things in `runtime` the spec is actually opinionated about, but you get the point)

If the goal is to decouple Cromwell from WDL, the most obvious target is the `runtime` section. If people need more control over their Cromwell experience the answer is to a) provide that information in a way which doesn't destroy workflow portability of the WDL and b) expose that via Firecloud if those users need Firecloud

FWIW one of my primary goals for WDL 1.0 is a massive redo of `runtime` including removing the arbitrariness of it. If things are implementation specific they can be passed in to that engine separately, which would also help maintain the portability of the workflow itself.

**Comment by geoffjentry** [comment]
Closing this. It doesn't belong in `runtime`, Firecloud doesn't allow for customization of workflow options directly, there are multiple ways to do this with standalone Cromwell, and the nuts and bolts of this are going to be finding their way into Terra
