### ISSUE TITLE
inline python-can't use a = {}

### ISSUE THREAD

**Issue by joshua-gould** [broadinstitute/cromwell#3027]
In inline python code, you're unable to create a dictionary using braces

**Comment by cjllanwarne** [comment]
Hey @joshua-gould! If possible I'd suggest making these sorts of questions in the [WDL forum](https://gatkforums.broadinstitute.org/wdl) in the future since your answer could also help others out.

As it turns out, I believe your question is also already answered there: https://gatkforums.broadinstitute.org/wdl/discussion/8721/how-can-i-include-in-a-wdl-script
