### ISSUE TITLE
Add ability to include/exclude subworkflows in the query endpoint

### ISSUE THREAD

**Issue by samanehsan** [broadinstitute/cromwell#3240]
The query endpoint currently returns a list of all workflows and subworkflows matching the query parameters. For the job manager UI, we want to show parent workflows in the list view so we include the `parentWorkflowId` in `additionalQueryResultFields` and then filter out any workflows that have a `parentWorkflowId`. This complicates paginating the response in the UI, since you might request a page of 100 workflows where half of them are subworkflows. 

It would be useful to add a parameter to exclude subworkflows from the response so that additional processing is not required after retrieving those results.

**Comment by kbergin** [comment]
We were running some scaling tests today in our cromwell. One of them was 60,000 workflows submitted with 1 subworkflow each. This was enough to essentially break JMUI, because we are doing a workaround to exclude the subworkflows after we query and after enough pagination, which is taking too long and timing out. Just for some recent context on this issue!

**Comment by kbergin** [comment]
I just realized that we essentially blocked ourselves because of the comment above, where we now have so many subworkflows that we can't stand up a job manager on that cromwell because it can't filter them out quickly enough on the JMUI server side to render the website. Our own fault, but we'll be happy to see this functionality go in!
