### ISSUE TITLE
use MySQL Server: 5.5.56-MariaDB error

### ISSUE THREAD

**Issue by 251505453** [broadinstitute/cromwell#3346]
cromwell-system-akka.dispatchers.service-dispatcher-19 ERROR - Error summarizing metadata
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"SUMMARY_STATUS_ENTRY" where ("SUMMARY_TABLE_NAME" = 'WORKFLOW_METADATA_SUMMARY_' at line 1

**Comment by geoffjentry** [comment]
Hi @251505453 - can you provide more information on what you're trying to do here? ie what's your setup, etc?

**Comment by 251505453** [comment]
SET sql_mode = 'ANSI_QUOTES';
https://mariadb.com/kb/en/library/sql-mode/

**Comment by 251505453** [comment]
Caused by: liquibase.exception.DatabaseException: Unknown column '' in 'where clause' [Failed SQL: UPDATE WORKFLOW_STORE_ENTRY
SET CUSTOM_LABELS = "{}"
WHERE CUSTOM_LABELS = ""]
new issues

**Comment by geoffjentry** [comment]
Hi @251505453 - I'll reiterate my request to provide more information on what you're doing, what your set up is, what version of cromwell you're using, etc. As it stands, this is not particularly actionable.

**Comment by 251505453** [comment]
cromwell-30.2.jar

**Comment by kshakir** [comment]
Hi ChenYong,

I'm closing this issue here on GitHub as Cromwell [30-16f3632 / 30.2](https://github.com/broadinstitute/cromwell/releases/tag/30.2) seems to run fine against a basic MariaDB 5.5.56.

I also tried changing the database initialization script to run with-and-without setting `SET GLOBAL sql_mode = 'ANSI_QUOTES';`.

If you're still running into problems, can you please create a post over in the [Ask the WDL team](https://gatkforums.broadinstitute.org/wdl/categories/ask-the-wdl-team) forum? There please provide as many logs and configuration files as possible (without passwords) so that your issue may be reproduced.

---

To test Cromwell with MariaDB I combined the following files and ran them from  an `issues_3346/` directory with `docker-compose up`.

- `issues_3346/compose/cromwell/app-config/application.conf`
- `issues_3346/compose/cromwell/Dockerfile`
- `issues_3346/compose/mysql/init/init_user.sql`
- `issues_3346/docker-compose.yml`

The files are in this archive: [issues_3346.tar.gz](https://github.com/broadinstitute/cromwell/files/2190721/issues_3346.tar.gz)

Cromwell started and connected to the db. I was able to browse to `http://localhost:80` and submit a workflow.
