### ISSUE TITLE
job scheduling on Mesos

### ISSUE THREAD

**Issue by matthdsm** [broadinstitute/cromwell#3461]
Hi,

Are there any plans to support a scheduler that can submit jobs to a mesos cluster (e.g. Chronos or whatever?)

Thanks
M

**Comment by geoffjentry** [comment]
Hi @matthdsm TBH this is the first time we've been asked, so not as of yet :) 

Less cheekily, we haven't heard a desire for this although it certainly could be done. If we start to hear from folks (such as yourself) that this is something that'd really be empowering for them we could put it on the roadmap

**Comment by matthdsm** [comment]
Well, here's hoping this gains some traction! Would be a nice addition!

M

**Comment by matthdsm** [comment]
Would it make you jealous if I told you there are CWL runners that do support Mesos? 👼 
https://github.com/BD2KGenomics/toil

**Comment by scalavision** [comment]
It would be very nice to support Mesos, as it is a very nice framework for in house cloud computing systems. Not everyone is able to launch their jobs into the cloud. I see you already have support for Yarn here: 

http://cromwell.readthedocs.io/en/develop/backends/Spark/

And we also have this:
```
A not so widely known fact is that Spark has its root in Mesos: it was initially developed at the AMPLab as a proof-of-concept Mesos framework to demonstrate how easy and fast it is to develop a distributed platform on top of Mesos
```
taken from here : 
* https://mesosphere.com/blog/spark-mesos-shared-history-and-future-mesosphere-hackweek/

Spark and Mesos was really closely integrated, though I see that Spark has created their own scheduler,  Mesos is still a very good way of running Spark jobs. It would be a very nice addition to the Chromwell framework! 

Mesos is used in many other Big Data cloud environments outside of the Bioinformatics pipelines.

**Comment by ruchim** [comment]
Hey @matthdsm, @scalavision 

A few questions around this request. Apologies as I'm new to the world of Mesos clusters -- but on a high level, can you help me understand what are the reasons to use Mesos over Yarn for running Spark jobs? Thanks!

**Comment by matthdsm** [comment]
Hi @ruchim,

Personally, the reason I'm asking for Mesos support is because we have a Mesos cluster available, but no yarn. It's awesome cromwell already supports yarn, but it'd be great to have even more options.

Cheers
M

**Comment by scalavision** [comment]
Hello @ruchim :-)

The Spark job will run just as good in Yarn as in Mesos, I am pretty sure about that. Main difference is that Mesos is much more advanced than Yarn. It is more scalable, both in terms of nr of nodes, nr of jobs, and types of jobs and applications. 

In Mesos, you can run both normal applications (web apps etc.), like you do in Kubernetes, and you can run compute / Big Data processing jobs in the same cluster. You can schedule both cpu and memory usage, not only memory usage as in Yarn. Mesos creates a virtual operating system on top of your cluster, kind of. Yarn is not capable of that as I know it.

You can even  run Yarn and Kubernetes on top of Mesos etc. Choosing Mesos over Yarn, will therefor make sense for many companies, because you get one system to rule them all. It might add more complexity also though ... I am a bit dated on this, Yarn might have evolved since I looked at it.

This article is good at explaining the difference:

https://www.oreilly.com/ideas/a-tale-of-two-clusters-mesos-and-yarn

Here is a nice summary of the main differences:
https://data-flair.training/blogs/comparison-between-apache-mesos-vs-hadoop-yarn/

Hope this give some answers :-)
