### ISSUE TITLE
Poor performance on small workflows

### ISSUE THREAD

**Issue by rasmuse** [broadinstitute/cromwell#3477]
I'm having problems using Cromwell for fast iteration on small workflows. I realize I might be using Cromwell for things it was not supposed to do, but since it is so very slow I thought I might ask anyway. Just so you understand my application, I'm not running bioinformatics pipelines: I'm rather interested in using WDL instead of Makefiles to do various scientific calculations. It's often a bunch of relatively simple Python or R scripts that I want to connect in a chain, and then sweep some parameters, etc. While developing and debugging the workflows (the majority of the time) I have a need for running and re-running single tasks or small sub-workflows many times. I was hoping I could use Cromwell to do this, but at present it just is too slow.

Let's say I run a tiny workflow like the [Hello world example](http://cromwell.readthedocs.io/en/develop/tutorials/FiveMinuteIntro/#step-2-writing-your-first-workflow-description) from Cromwell's docs:
```wdl 
workflow myWorkflow {
    call myTask
}

task myTask {
    command {
        echo "hello world"
    }
    output {
        String out = read_string(stdout())
    }
}
```

I'm on Ubuntu 16.04, I start a Cromwell server and wait for it to spin up. Then

```bash
$ time /usr/lib/jvm/java-8-openjdk-amd64/bin/java -jar cromwell-31.jar submit wf.wdl 
[2018-04-04 15:37:15,92] [info] Slf4jLogger started
[2018-04-04 15:37:17,06] [info] Workflow ab6ec0d5-20d2-4113-a58a-0b0e15097476 submitted to http://localhost:8000

real	0m2.536s
user	0m5.316s
sys	0m0.292s
```

Just submitting the job takes 2.5 seconds wall clock time. Then watching the server do the job takes another 21 seconds:

```bash
2018-04-04 15:37:17,001 cromwell-system-akka.dispatchers.api-dispatcher-117 INFO  - WDL (Unspecified version) workflow ab6ec0d5, so essentially the job is equivalent to-20d2-4113-a58a-0b0e15097476 submitted

[various log outputs]

2018-04-04 15:37:38,440 cromwell-system-akka.dispatchers.engine-dispatcher-6 INFO  - WorkflowExecutionActor-ab6ec0d5-20d2-4113-a58a-0b0e15097476 [UUID(ab6ec0d5)]: Workflow myWorkflow complete. Final Outputs:
{
  "myWorkflow.myTask.out": "hello world"
}
```

As far as I understand, it's not even doing any of this in a docker environment. Am I doing something wrong, or is it expected that there is such an overhead? Is there anything I can do to speed it up?

Many thanks for the great work.

**Comment by geoffjentry** [comment]
Hi @rasmuse - a few thoughts. In terms of the submit time keep in mind things like JVM initialization. Calling individual invocations of a java program like that for what's effectively a blink of an eye operation is never going to be ideal from a performance perspective. If you're submitting to a Cromwell server consider using something like `curl` instead. 

On the second part, there are a few things potentially going on here. First is that Cromwell doesn't necessarily immediately start a workflow. It scans every `n` seconds for new workflows to start, which defaults to `20`. In a worst case scenario `21` of your `20` seconds could be due to that, although that seems unlikely. You can make that time window shorter by overriding the `system.new-workflow-poll-rate` configuration setting to something smaller, e.g. `1`. Even then, there's a some overhead in there as ultimately we're trying to optimize for a case that's not running single, extremely short tasks.

I just ran the moral equivalent of a hello world workflow locally with that config setting set to 1 second. The workflow was picked up for execution at `11:08:44` and registered as complete at `11:08:51` with exactly half of that time spent with the system running the underlying job (i.e. not in Cromwell) so it might be worth revisiting this w/ a combination of using `curl` and speeding up the workflow polling rate.

That said while I'd love you to continue to use Cromwell/WDL, it might not wind up being the best tool for your job. If these workflows are purely for yourself & you don't intend on building them up over time and/or distributing them to others, you might want to check out Snakemake which is more intended to be a direct Makefile replacement.

**Comment by rasmuse** [comment]
Hi @geoffjentry - thanks for the prompt and detailed response.

It makes sense to submit using curl instead. That might save most of the 2.5 seconds. But since your fast-polling hello world test still took 7 seconds from pickup to completion, I still think this would be frustratingly slow.

I'm familiar with Snakemake (and about two dozen other similar tools to be found scattered across the web) but I think WDL is better in a number of ways. The main points that I like are (1) that the workflow language is clearly separated from the execution engine, (2) that the language is much more human-readable than CWL, and (3) the possibility to serialize/deserialize values, e.g., so that (3a) simple operations, e.g., concatenation of different results can be done in the workflow language and (3b) one can do things like mapping a task over a set of values coming out of another task. It is also nice that (4) there is a rather solid set of backing organizations behind WDL and Cromwell. As far as I know, this combination of properties gives WDL a rather unique value proposition.

Maybe there is room for a simpler local-only WDL execution engine focused on speed and rapid iteration. That could be used for development and then the execution of production workflows on various cloud backends etc could still be done by Cromwell. I was dabbling one weekend a few months ago with a local-only Python compiler/execution engine for WDL. If optimal execution speed is not a must, it does not look too hard to support most of the WDL spec on a local machine.

I'm closing this issue for now. Thank you again for the input!

**Comment by geoffjentry** [comment]
Hi @rasmuse That's fair, and again I'm not going to try too hard to sway you away from WDL :)

I'd be very much in favor of more WDL runner implementations out there if that's a path you wanted to explore. 

It's pretty out of date but you might find some inspiration in [PyWDL](https://github.com/broadinstitute/pywdl). If you go back far enough in its history it was even a simple python based WDL runner.

If you're interested in Go, there's also [Maple](https://github.com/scottfrazer/maple) from the originator of WDL, although it's certainly out of date w/ the latest WDL features.

**Comment by cjllanwarne** [comment]
Hi @rasmuse, I lead the Cromwell Languages team here at the Broad (a small offshoot team from the main Cromwell team). Ultimately, Cromwell will always aim to be a production scale engine, but my team is especially interested in anything that makes reading, writing, testing, experimenting with and debugging workflows easier...

If you're serious about trying to make an "optimized for small local tasks" implementation of a WDL engine, that definitely sounds like something that could definitely help out our workflow authors too... so do let me know if it goes anywhere and if we can help out at all! Thanks!
