### ISSUE TITLE
Cromwell production goes down, "too many files open"

### ISSUE THREAD

**Issue by danbills** [broadinstitute/cromwell#3716]
Tracking production issue that occurred on May 30th at 6pm.

Cromwell had 65K files open, reboot resolved the issue.

**Comment by mcovarr** [comment]
Kristian saw this again last night. I believe Henry made some config adjustments to up the limit in the Cromwell container and restarted.
![image](https://user-images.githubusercontent.com/10790523/41095375-3a47e138-6a1f-11e8-8f14-19a3cb1b7d81.png)

**Comment by hjfbynara** [comment]
Some information that may assist in debugging what is going on.  I logged onto production to see what the current openfile count is and it is over 90K.  Since we now have sufficient headroom to further investigate (ie java is not running out of open file handles) - I ran lsof on the java proc to see what it tells me. 

First I looked at the beginning part of the "path/name" for the open file to see if there was some common part.

 awk ' { print $9 } ' < /tmp/lsof.out | cut -d '/' -f2 | sort | uniq -c | sort -nr
  50277 pipe
  25137 [eventpoll]
  14242 cromwell-workflow-logs
   1094 protocol:
     69 (stat:
     17 usr
     12 tmp
      6 dev
      2 etc
      2
      1 var
      1 app
      1 NAME

Obviously "pipe" and "eventpoll" are important areas to investigate to see if this is normal behavior or something odd.

The third largest consumer "cromwell-workflow-logs" seemed interesting and if you look more closely I noticed that of the 14k over 11k are files that no longer exist (were deleted) but cromwell is maintaining an open file handle to it.  

egrep cromwell-workflow-logs /tmp/lsof.out | awk ' { print $NF } ' | sort | uniq -c | head -4
  11541 (deleted)
      1 /cromwell-workflow-logs/workflow.0005b906-d7be-4214-9943-0647a92c2c8e.log
      1 /cromwell-workflow-logs/workflow.000c5b14-0da4-4c2c-9a3b-f50377471820.log
      1 /cromwell-workflow-logs/workflow.001655a7-2c75-4a0f-b7cc-ba8ec96781ec.log

I also ran ls on the directory inside the container to see how many files exist.  Of course the exact numbers don't line up because all these commands were run at different times (lsof was a snapshot ran at a specific time and my ls command is current time)

docker exec -it cromwell_app_1 ls /cromwell-workflow-logs | wc -l
2699

So at least one place that warrants further investigation is the code that reads/writes the cromwell-workflow-logs - something in there is not closing their file handle.

**Comment by mcovarr** [comment]
Thanks Henry, I'm currently on rotation so I'll look into the workflow log issue. Is there any way to get more detail on the `pipe` or `[eventpoll]` categories?

**Comment by mcovarr** [comment]
Unsurprising update: Cromwell is definitely leaking workflow log file handles.

**Comment by danbills** [comment]
The current strategy is to disable metrics and see what happens.  

Alpha ran for about 12 hours yesterday into today and should be reflected in collectd metrics which are submitted independently of Cromwell.  Look for `collectd.gce-cromwell-alpha401`. If those metrics show a steady (not increasing) file handles, then our metrics lib is the issue.

I think we should do the same for sentry although it is used much less often and I kinda doubt it is the source.

Finally I suspect our polling of PAPI as we're doing that all day long.  Not sure of the best way to track that they're open/closed.  Maybe a NewRelic counter or something similar that could be used to correlate to open files graph.
