### ISSUE TITLE
Issue coercing Int to String inside of a Map

### ISSUE THREAD

**Issue by samanehsan** [broadinstitute/cromwell#4131]
I'm getting an error from Cromwell `Failed to coerce one or more keys or values for creating a Map[String, Int?]` when defining an object as an input to a task that consists of a string, file and int. I would expect the Int to get converted into a string, but the error makes it seem as if Cromwell is trying to convert all of the values into integers.

Here is the part of the WDL that's throwing the error: https://github.com/HumanCellAtlas/pipeline-tools/blob/c949cb5ffa2df8f2a7fc7d7a4c34478e8eadbf34/adapter_pipelines/cellranger/adapter.wdl#L222

**Comment by ruchim** [comment]
@samanehsan -- is this blocking, or have you found a workaround?

**Comment by cjllanwarne** [comment]
@samanehsan there is a problem here (maps that are made using `String`s and `Int`s should evaluate to `Map[X, String]` rather than `Map[X, Int]`, but in your case the real problem is you're using `Map`s to instantiate `Object`s - which is much nicer to do using the object literal syntax. In your example:

```wdl
      other_inputs = [
        object {
          name: "sample_id",
          value: GetInputs.sample_id
        },
        object {
          name: "reference_name",
          value: reference_name
        },
        object {
          name: "transcriptome_tar_gz",
          value: transcriptome_tar_gz
        },
        object {
          name: "expect_cells",
          value: expect_cells
        }
      ]
```

This has the added bonus when you switch to WDL 1.0 and start using `struct`s that we can type-check your object instantiations at validation time (we can't do that with map => object coercions)
