### ISSUE TITLE
flaky requester pays localization tests

### ISSUE THREAD

**Issue by danbills** [broadinstitute/cromwell#4233]
One of the request pays tests is failing fairly frequently.

![image](https://user-images.githubusercontent.com/165320/46824117-ef956c80-cd5d-11e8-88f1-7c17678b8329.png)

**Comment by Horneth** [comment]
@danbills OOC when was this screenshot taken ? Last timed I looked at the requester pays failures, I sampled a few and they were due to the alpine issue IIRC so I'd have expected them to stop happening by now.
Last one I see on develop from sentry was Sept 24th here: https://sentry.io/broad-institute/cromwell/issues/650196050/events/?query=ci_env_branch%3Adevelop

**Comment by danbills** [comment]
It was taken as I wrote the ticket, so 4 days ago

**Comment by Horneth** [comment]
I think I found the one you are talking about

![screen shot 2018-10-15 at 11 28 47 am](https://user-images.githubusercontent.com/2978948/46960909-92efc580-d06d-11e8-97fe-d81ef63da81a.png)

The failure reason is 

```
Task requester_pays_engine_functions.functions:NA:1 failed. The job was stopped before the command finished. PAPI error code 2. Execution failed: pulling image: docker pull: running ["docker" "pull" "ubuntu@sha256:de774a3145f7ca4f0bd144c7d4ffb2931e06634f11529653b23eba85aef8e378"]: exit status 1 (standard error: "error pulling image configuration: received unexpected HTTP status: 502 Bad Gateway...
```

which is not related to the requester pays feature but rather yet another dockerhub flaky response that we should ask google to retry IMO.

**Comment by Horneth** [comment]
I let Aaron know about this dockerhub failure and he'll add it to the ones being retried. I think we can close this for now.
