### ISSUE TITLE
Graceful shutdown of cromwell wrt workflow state and heartbeats

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#4242]
P2 - to optimize the case of restarting a single cromwell, upon shutdown the heartbeat related information (server, timestamp) should be deleted so the workflow is immediately picked up on restart rather than after the timeout period

**Comment by mcovarr** [comment]
Cromwell should already [clear workflow store heartbeats](https://github.com/broadinstitute/cromwell/blob/develop/engine/src/main/scala/cromwell/server/CromwellShutdown.scala#L165) on graceful shutdown. If Cromwell is being shut down gracefully and this isn't happening then there's a bug, but if Cromwell is not being shut down gracefully then stale heartbeats would be the expected behavior.

**Comment by danbills** [comment]
@kcibul @mcovarr it sounds like this is already the case and thus this ticket should be closed.  If not please re-open
