### ISSUE TITLE
Fix AWS Cron

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#4314]

**Comment by kshakir** [comment]
A/C:
- AWS Jenkins success restored
- **At least one** `standardTestCase` WDL is turned on in Travis too, so that these issues are caught sooner.

https://github.com/broadinstitute/cromwell/blob/910183057169726ec9949097077f471ec90c9ecb/src/ci/bin/testCentaurAws.sh#L27-L28

May also be related to #4294.

**Comment by ruchim** [comment]
I believe this is closed by https://github.com/broadinstitute/cromwell/pull/4326
