### ISSUE TITLE
Cromwell ignoring CWL's tmpdirMin and outdirMin

### ISSUE THREAD

**Issue by multimeric** [broadinstitute/cromwell#4507]
I've been getting the following GATK error when running a CWL pipeline on Cromwell:
```
##### ERROR MESSAGE: Writing failed because there is no space left on the disk or hard drive. Please make some space or specify a different location for writing output files.
``` 
To attempt to resolve this, I added the following requirement to the GATK tool in question:
```yaml
- class: ResourceRequirement
  coresMin: 2
  ramMin: 8000
  tmpdirMin: 100000
  outdirMin: 100000
```

However, this didn't resolve the GATK issue. I looked further into the Cromwell source and I found the following code: https://github.com/broadinstitute/cromwell/blob/44297611175c8a2a92ee71f0fa9c34419b69f0b8/cwl/src/main/scala/cwl/requirement/RequirementToAttributeMap.scala#L46-L57

To me, it looks like these values are being thrown out (I could be wrong). 

Should we not convert these into a [`disk` statement](https://cromwell.readthedocs.io/en/develop/RuntimeAttributes/#disks) that Cromwell can understand and implement?

**Comment by TMiguelT** [comment]
I've had a quick look at the code but I'm struggling with the Scala as usual, so I don't think I'd be up to making a PR to fix this. Incidentally, will the tmpdirMin and outdirMin statements both map to the `disk XXX SSD`, or will they be different disks? I suppose they should be, in order to make sure each has at least the amount of disk space specified. And if they are different disks, how will I know where to mount them? I can't work out what the TMPDIR and HOME are being set to in a Cromwell job (and actually it will vary depending on the backend, I imagine)

**Comment by ruchim** [comment]
@cjllanwarne would you mind looking at this question when you get a chance?
