### ISSUE TITLE
WaaS /describe: zip imports

### ISSUE THREAD

**Issue by aednichols** [broadinstitute/cromwell#4572]
Add zip import upload option to Swagger, wire it through to `cromwell.services.womtool.Describer`, and add the resulting resolver to the `getWomBundle` calls.

**Comment by cjllanwarne** [comment]
TBH I'd put this right at the bottom of the priority list, in the "hope zips become outdated before we work on this" category.

**Comment by ruchim** [comment]
I'm advocating removing it from the Epic for now, and say that MVP for this epic only supports http imports--as the users driving this case are Terra users, and they can't use zip's at all.

**Comment by aednichols** [comment]
If one day people want to use Womtool via `api.firecloud.org` and need to use zips this is the issue to implement. Right now it is not relevant to what we think of the WaaS effort to support Terra.

**Comment by patmagee** [comment]
@cjllanwarne not having this consume the imports of a workflow has actually lead us to create our own service for describing workfklows as a json schema. having a JSON schema returned is actually quite practical since we can build some pretty UI's around it with existing tools

Is this still low down on the priority list?

**Comment by aednichols** [comment]
Hi @patmagee – it's actually very easy for us to implement this, we deferred doing so due to lack of interest. You should feel free to ask for help early instead of building your own thing 😀

**Comment by aednichols** [comment]
*perceived lack of interest
