### ISSUE TITLE
CWL workflow that runs in cwl-runner does not run in cromwell (local back end)

### ISSUE THREAD

**Issue by dtenenba** [broadinstitute/cromwell#4587]
Backend:
Local, no conf file

Workflow: Files are here:
https://github.com/FredHutch/reproducible-workflows/tree/master/CWL/SingleStepWorkflow

Details (see also [this post](https://gatkforums.broadinstitute.org/wdl/discussion/23265/cwl-workflow-fails-running-locally#latest)):

I can run this workflow just fine using cwltool/cwl-runner as follows:

```
cwl-runner bwa-memWorkflow.cwl localInputs.yml
```

When I try and run it with cromwell I get an error that "The job was aborted from outside Cromwell" but I definitely did not abort it myself.

Here is the command I used to run this workflow in Cromwell:

```
java -jar cromwell-36.jar  run bwa-memWorkflow.cwl -i localInputs.yml -p bwa-pe.cwl.zip
```

(`bwa-pe.cwl.zip` just contains the dependency `bwa-pe.cwl`)

And here's the full output of it:

https://gist.github.com/dtenenba/61bcf60f129b817cd894ee222789369a

My ultimate goal is to switch over to the AWS Batch back end (in case you are wondering why I don't just stick with cwltool) but first I wanted to get the workflow running locally in cromwell.

Any ideas about this?

**Comment by vortexing** [comment]
Note:  We currently can't test CWLs on AWS with v37 Cromwell because of the input/output staging issue I mentioned over with the call caching problems.  We just get the input/output error and the  jobs won't move forward enough to even see what other issues might arise.  

Related to:
https://github.com/broadinstitute/cromwell/issues/4563

That's a deal breaker for our institution.  @wleepang These are all related.
