### ISSUE TITLE
Add cromwell version number to metadata

### ISSUE THREAD

**Issue by gbggrant** [broadinstitute/cromwell#4668]
Hi,

I recently ran a workflow on our dev server which was running cromwell 37.  Right around that time dev-ops reverted it to 36.   I wanted to confirm that it ran on 37, but couldn't find anything in the metadata to indicate the version of cromwell that was running when the workflow executed.

I think it would be great to have that information available.

Thanks.

FYI - here's the metadata for the workflow in question:
https://cromwell.gotc-dev.broadinstitute.org/api/workflows/v1/0ac19869-db74-45ba-a785-9e3eebe4103d/metadata

**Comment by mcovarr** [comment]
I included some changes in #4961 that might work for this enhancement request. The changes in that PR publish "workflowProcessingEvents" for workflow pickup, release, and completion. The first two events types can be multi-valued since Cromwell can be restarted and possibly upgraded during the execution of a workflow. Sample metadata from a simple run:

```
{
  "workflowName": "wf_hello",
  "workflowProcessingEvents": [
    {
      "cromwellId": "cromid-4db4123",
      "timestamp": "2019-05-13T15:00:22.152Z",
      "cromwellVersion": "41-07606c8-SNAP",
      "description": "Finished"
    },
    {
      "cromwellId": "cromid-4db4123",
      "description": "PickedUp",
      "timestamp": "2019-05-13T15:00:10.879Z",
      "cromwellVersion": "41-07606c8-SNAP"
    }
  ],
...
```
