### ISSUE TITLE
Cromwell expects docker images to be run as root user

### ISSUE THREAD

**Issue by agduncan94** [broadinstitute/cromwell#472]
When running a docker image through Cromwell, it assumes that you are the root user for the docker container.

I was trying to run a docker image which has to be run as a non-root user, so they don't have access to the root user home folder (/root).  The problem with this is that Cromwell will place any files you pass to the container in the /root directory, so you need to be the root user or else you will get a permission error.

**Comment by abuchanan** [comment]
I'm also running into this. Would be nice to get some guidance on a fix from the cromwell team.

Ideally, maybe both the user and volume mount location are configureable? Not sure yet what the best fix is.

**Comment by geoffjentry** [comment]
@kcibul This is the ticket I mentioned the other day

**Comment by tomkinsc** [comment]
I just ran into this. Even if it is not a best practice, it is certainly common for container users to be non-privileged, so this issue will definitely impact others as well. It seems reasonable to be able to specify the user and volume mount locations, since it's just a change to the `docker run` call. 

Is `dockerOutputDir` only applicable to the HtCondor backend?

**Comment by mcovarr** [comment]
See also #375

**Comment by mcovarr** [comment]
Looking at this with Cromwell 24, the user can be specified with a config like:

```
  default = "Local"
  providers {
    Local {
      actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"
      config {
        runtime-attributes = """
        String? docker
        String? docker_user
        """
        submit-docker = """docker run --rm ${ "--user " + docker_user } -v ${cwd}:${docker_cwd} -i ${docker} /bin/bash ${docker_cwd}/execution/script"""
        .
        .
        .
```

The WDL can pass in `docker_user` as a runtime attribute, which could be an expression involving an input or just a hardcoded value.

But even with a container path not under `/root`, there are currently permissions problems that prevent this from working due to the different users inside and outside the Docker container.  It may be possible to `chmod` and `umask` our way past these problems, but I need to think through the security implications of doing so.  Maybe making this more liberal behavior an opt-in configuration value in the backend config would be okay?

**Comment by mcovarr** [comment]
I have some changes for this on a branch that I'd like to try with a realistic test case.  Can anyone volunteer an example?  Thanks!

**Comment by tomkinsc** [comment]
@mcovarr: A simple print of the help text from any of our Docker images would fit the bill:
https://hub.docker.com/r/broadinstitute/viral-ngs/tags/

The relevant command would be: `read_utils.py --help` (should exit 0):

```
task dockerTest {
  command {
    taxon_filter.py --help
  }

  runtime {
    memory: "8GB"
    docker: "broadinstitute/viral-ngs"
  }
}
```

**Comment by mcovarr** [comment]
Thanks @tomkinsc, that works.  The non-root support changes have now been merged to develop.
