### ISSUE TITLE
Access to runtime attributes within tasks

### ISSUE THREAD

**Issue by Xophmeister** [broadinstitute/cromwell#4741]
It seems that the protocol for setting runtime attributes is to do so within the task, thus allowing expressions based on their values. Say,

```wdl
task foo {
  Int cpus

  runtime {
     cpus = cpus
  }

  command {
    ./my_binary --threads ${cpus * 2}
  }
}
```

However, a lot of the time, it's not appropriate (in a "separation of concerns" sense) to thread the value through the task invocation. For example, you may be setting a Unix group under which all data should be accessed, defining credentials, etc. We're doing this by using the `default_runtime_attributes`, passed in as workflow options. However, these are not visible to the task.

This is what we'd like to be able to do, for example:

Workflow Options:
```json
{
  "default_runtime_attributes": {
    "AUTH_USER": "foo",
    "AUTH_TOKEN": "bar"
  }
}
```

Workflow:
```wdl
task {
  command {
    export AUTH_USER="${AUTH_USER}"    # Taken from default_runtime_attributes
    export AUTH_TOKEN="${AUTH_TOKEN}"  # Taken from default_runtime_attributes
    ./my_authenticated_command
  }
}
```

At the moment, this will fail, as `AUTH_USER` and `AUTH_TOKEN` are not defined within the task. Even if you explicitly define it in the task (`String AUTH_USER`, etc.), Cromwell won't automatically seed this from the default options.

I can see why it would be useful to define the inputs in the task, for clarity's sake. I'm just thinking out aloud -- so this is very much half-baked -- but perhaps an option would therefore be to have an additional keyword that made it explicit that the task value was to be taken from options:

```wdl
task {
  Int something
  runtime String AUTH_USER   # "runtime" implies this is from the runtime attributes (default or otherwise)
  runtime String AUTH_TOKEN  # Raise an error if undefined or modified within the task

  command {
    export AUTH_USER="${AUTH_USER}"
    export AUTH_TOKEN="${AUTH_TOKEN}"
    ./my_authenticated_command -n ${something}
  }
}
```

**Comment by geoffjentry** [comment]
@Xophmeister Ultimately this is going to need changes to the WDL spec and thus a conversation over in the [OpenWDL group](www.openwdl.org), although your issue does start entering the murky grey area between WDL and Cromwell (which admittedly exists due to WDL's heritage as originally being a product of the Cromwell team).

You're able to reference values in `runtime` because the WDL spec allows it. However, there's no notion in WDL of `default_runtime_attributes`, that's a purely Cromwell concept. Thus if Cromwell were to allow this, it'd encourage WDLs which would fail elsewhere. 

My own $0.02 is that `runtime` is horribly broken and needs to be rebuilt from the ground up (again, over in OpenWDL, not here). Since history has shown that there's always some path to fixing `runtime` which **doesn't** require my burn it all down approach a good first step might be to suggest an official system of defaults over there.

I'm going to close this issue as I don't believe there's anything reasonable we can do from the Cromwell side. If, given the context I provided above, you disagree (e.g. perhaps I misunderstood the ask) let me know and we might reopen it.
