### ISSUE TITLE
Fix broken aws globbing centaur tests

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#4855]
draft3_glob_access
globbingindex
globbingscatter
draft3_globs

**Comment by kshakir** [comment]
Pretty sure this was fixed by @delocalizer way back in #4109.

However during my debugging of `globbingBehavior` for #4854, it seemed something was rotten in the state of `GenomicsHighPriorityQue-c1ed17c72de5fcb`.

I still don't 100% know the setup for the AWS queues, but I think a) perhaps we just never updated ecs-proxy over in quay?, and/or b) maybe the ARN "fixes" in  #4896/#4902 pulled in Conrad's fixes?

Either way #4958 stops excluding the tests.
