### ISSUE TITLE
GB vs GiB change affecting users 36 -> 38

### ISSUE THREAD

**Issue by aednichols** [broadinstitute/cromwell#4906]
https://broadinstitute.slack.com/archives/C1EH66VCM/p1556219943031700

I haven't stopped to reason out whether there is anything we can/should do to fix, this is a tricky area.

One PR I was looking at that seems to fall in the 36 -> 38 timeline is https://github.com/broadinstitute/cromwell/pull/4489 - doesn't mean that change introduced a bug though, maybe the previous way was wrong!

cc @samanehsan

**Comment by samanehsan** [comment]
I was mainly confused that `(size(file, "G")` returns a size in "GiB" in Cromwell 38, when it used to return a size in "G" in Cromwell 36

**Comment by aednichols** [comment]
I think there is a natural argument to be made that `disk_size = size(file)` should always work.

**Comment by aednichols** [comment]
@samanehsan what if you use `size(file, "GB")`?

WDL 1.0 spec:

>Supported units are KiloByte ("K", "KB"), MegaByte ("M", "MB"), GigaByte ("G", "GB"), TeraByte ("T", "TB") as well as their binary version "Ki" ("KiB"), "Mi" ("MiB"), "Gi" ("GiB"), "Ti" ("TiB"). Default unit is Bytes ("B").

**Comment by samanehsan** [comment]
Let me try that out! Looking at this again, I wonder if it is actually correctly returning a number in GB here: https://github.com/HumanCellAtlas/skylab/blob/master/library/tasks/StarAlignBamSingleEnd.wdl#L10

But then when it is passed into the `disks` parameter as "local-disk 60G SSD" it gets converted to "local-disk 56GiB SSD"?

**Comment by samanehsan** [comment]
Oh it just gets a number so nevermind...

**Comment by ruchim** [comment]
```
size(f) ==> 5419250 Bytes (base-10)
size(f, "G") ==> 0.005047069862484932 (base-2)
size(f, "GB") ==> 0.005047069862484932 (base-2)
size(f, "GiB") ==> 0.005047069862484932 (base-2)
```

**Comment by ruchim** [comment]
Units used by GCS:
```5.17 MiB     gs://gatk-test-data/wgs_fastq/NA12878_20k/H06HDADXX130110.1.ATCACGAT.20k_reads_1.fastq```

**Comment by JZL** [comment]
Hi,

Following up on this, for local SSD's this distinction has big consequences because I can only increase by integer number of 375 GiB chunks. I think it would be work modifying the documentation [here](https://github.com/broadinstitute/cromwell/blob/17efd599d541a096dc5704991daeaefdd794fefd/docs/RuntimeAttributes.md?plain=1#L194) to reference that it's in 375 G _i_  B chunks ([docs](https://cloud.google.com/compute/docs/disks)) and that, as far as I can tell, if I do:

```
disks: "local-disk 100 LOCAL"
```
then it's 100 GiB (or at least in all recent wdl/cromwell/terra) runs.  I ssh'd into one of the terra instances and was messing with `df -H` and `df -h` but then got myself more confused :-)
