### ISSUE TITLE
JobExecutionTokenDispenserActor crashes not infrequently

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#4908]
The singleton `JobExecutionTokenDispenserActor` seems to crash quite a bit with no cause currently known. The default Akka supervision strategy causes JETD to be restarted, but the reincarnated JETD knows nothing of its predecessors' token allocations. This will cause tokens to be dispensed as if none are outstanding and returned tokens to produce error messages like:

```
2019-04-26 19:40:20 [cromwell-system-akka.actor.default-dispatcher-1109] ERROR c.e.w.t.JobExecutionTokenDispenserActor - Job execution token returned from incorrect actor: 202ffd24-a696-4edc-b832-a75f1127fdb4-EngineJobExecutionActor-Gatk3BamToGVCF.PrintReads:1:1
```

JETD restarts in production can be found by looking for `"log token queue events"` in Kibana where there is no corresponding Cromwell restart.

**Comment by cjllanwarne** [comment]
Symptoms

Issue:

- An assumption in the token dispenser actor (that none of the internal queues were ever empty) turned out to not always be true
- As a result, not infrequently an attempted `dequeue` would cause the `JobExecutionTokenDispenserActor` to crash and be restarted - zeroing out all known token dispensations *and* all known actors waiting for tokens.
- The overall consequence of this was that jobs would submit their request for exeution tokens and be added to a queue. But that queue was lost when the `JobExecutionTokenDispenserActor` was restarted and therefore the jobs would sit forever waiting for a token which was never sent to them.

The fix:
- First, add a sanity check before calling `dequeue`. If the queue is empty, don't do it. But hopefully will now be a redundant check thanks to:
- Second, one situation was identified which would lead to this state when token-requesting-actors were aborting before a token was dispensed. If that left the token queue for that hog group empty then the queue was not being correctly removed from the `JobExecutionTokenDispenserActor` - thus leaving an empty queue behind and triggering the "dequeue on an empty queue" bug.

**Comment by carbocation** [comment]
Out of curiosity, does this seem to be related to #4914 as well?

**Comment by cjllanwarne** [comment]
@carbocation I think these are different cases - in #4914 the jobs are being run by Cromwell but fail to reach PAPI. In this issue the jobs were not even selected by Cromwell to be started.
