### ISSUE TITLE
NVIDIA Driver version upgrade

### ISSUE THREAD

**Issue by sharmaashish** [broadinstitute/cromwell#4942]
Cromwell appears to lock virtual machines to the nvidia driver 390.46 

https://github.com/broadinstitute/cromwell/blob/db19bada612dbbec3c3fea5e12fab83666bffea8/supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/PipelinesApiRuntimeAttributes.scala#L23

This becomes problematic because this driver is incompatible with CUDA 10, which is required for the stable release of TensorFlow. GCP recommends using 410.79 or higher. 
https://cloud.google.com/compute/docs/gpus/add-gpus#install-driver-script

Could the upcoming release move over to the higher version? The upgrade to the newer driver version should not break driver compatibility (famous last words)
https://docs.nvidia.com/deploy/cuda-compatibility/index.html#binary-compatibility

**Comment by sharmaashish** [comment]
Could the driver version be upgraded to use the newer 410 (the default on GCP)

**Comment by cjllanwarne** [comment]
I have some good news for you! The upcoming changes in https://github.com/broadinstitute/cromwell/pull/4939 should satisfy this request by letting you specify the driver version right next to the docker image and GPU requirements in the `runtime` section.

That PR needs a little tidying up but should be ready to good relatively soon.

**Comment by sharmaashish** [comment]
Thank you. Looking forward to kicking the tires on this release.
What would be the default value of the driverVersion? It doesn't look like its a required attribute (??), so why not let GCP pick the stable one?

**Comment by sharmaashish** [comment]
@cjllanwarne 
Is there a reason you guys are leaving the default driver version to 390.xx and not the newer 410.xx?

Unless PAPI v2 insists that you provide a driver version, why not make the driver version optional and let GCP pick the driver suitable for the selected GPU?

**Comment by cjllanwarne** [comment]
@sharmaashish that's a great point. I _suspect_ (but haven't checked this) that if we don't specify any driver version then the VM we receive will spin up with a GPU attached, but no driver installed. So it's not "required" in that sense, but if you want to use GPUs then perhaps it is...

I think it would be appropriate to open an issue to "Update the default Nvidia GPU version in PAPIv2" with this suggestion (or maybe re-open this issue one with an updated title and description - I'll leave that up to you).

I'll also say that since you've already identified the line in the code and the change you want to make, we always appreciate PRs from motivated contributors!
