### ISSUE TITLE
Solving the simultaneous singularity build using flock

### ISSUE THREAD

**Issue by TMiguelT** [broadinstitute/cromwell#5063]
Further to the discussion in #4635, I've been thinking about a more elegant way to solve the awkwardness of running a scatter while using Singularity on HPC. The major issues include:
* We run N `singularity build`s, for a scatter over N items, which wastes time and CPU, and writing N large images to the filesystem simultaneously will presumably challenge the filesystem.
* We have to store N `.sif` images, which wastes space while the job is running
* We have to delete the image after each `singularity build`

My first proposed solution was #4673, which would solve the problem but require a pull request to introduce a new hook to Cromwell. And it doesn't look like the Cromwell team have been able to prioritise this. 

My new thought is that we could use file locks (e.g. `flock` on linux) to deal with this issue, so that the first worker to run will create a file lock, then all subsequent workers will encounter that lock, and wait until it's removed before attempting to build or run the image.

For example, we currently recommend this `submit-docker` configuration:

```
        submit-docker = """
            # Ensure singularity is loaded if it's installed as a module
            module load Singularity/3.0.1
            
            # Build the Docker image into a singularity image
            DOCKER_NAME=$(sed -e 's/[^A-Za-z0-9._-]/_/g' <<< ${docker})
            IMAGE=${cwd}/$DOCKER_NAME.sif
            if [ ! -f $IMAGE ]; then
                singularity pull $IMAGE docker://${docker}
            fi

            # Submit the script to SLURM
            sbatch \
              --wait \
              -J ${job_name} \
              -D ${cwd} \
              -o ${cwd}/execution/stdout \
              -e ${cwd}/execution/stderr \
              -t ${runtime_minutes} \
              ${"-c " + cpus} \
              --mem-per-cpu=${requested_memory_mb_per_core} \
              --wrap "singularity exec --bind ${cwd}:${docker_cwd} $IMAGE ${job_shell} ${script}"
        """
```

I'm instead proposing this. Note the use of a single shared image directory (`/singularity_cache` in this example), and the use of `flock` to ensure the submit scripts aren't competing with each other:

```
        submit-docker = """
            # Ensure singularity is loaded if it's installed as a module
            module load Singularity/3.0.1
            
            # Determine the filepath to the image
            DOCKER_NAME=$(sed -e 's/[^A-Za-z0-9._-]/_/g' <<< ${docker})
            IMAGE=/singularity_cache/$DOCKER_NAME.sif

            # Wait for an exclusive lock on the image 
            (
                flock --exclusive 200
                # Build the image
                if [ ! -f $IMAGE ]; then
                    singularity pull $IMAGE docker://${docker}
                fi
            ) 200>/var/lock/$IMAGE

            # Submit the script to SLURM
            sbatch \
              --wait \
              -J ${job_name} \
              -D ${cwd} \
              -o ${cwd}/execution/stdout \
              -e ${cwd}/execution/stderr \
              -t ${runtime_minutes} \
              ${"-c " + cpus} \
              --mem-per-cpu=${requested_memory_mb_per_core} \
              --wrap "singularity exec --bind ${cwd}:${docker_cwd} $IMAGE ${job_shell} ${script}"
        """
```

I haven't tested this on our HPC cluster (it's down for maintenance sadly!), but I'm interested if this makes sense as something we could get into the containers tutorial in order to recommend to users. @illusional, @vsoch @geoffjentry

**Comment by vsoch** [comment]
I'm just reading a bit [more](https://linux.die.net/man/1/flock) about `flock` - so with `-x` the idea is that you are creating a write lock - this means that this particular script will be run by many workers, and the first that gets to creating the lock will get it, continue, and do the build.

```
-s, --shared
Obtain a shared lock, sometimes called a read lock.
-x, -e, --exclusive
Obtain an exclusive lock, sometimes called a write lock. This is the default.
```
I'm wondering - what would be the return code for the second worker that cannot create the lock? What in the above says "Try to make the lock, if it doesn't work, come back and try again (and do this until the container is available.) 

Overall I think this is a really important thing to think about - aside from cluster resources, if you are pulling an image from a remote registry, that might have negative consequences for the registry.

**Comment by vsoch** [comment]
I also wouldn't be sparse with the variables, for some future user coming to read this, I would use `--exclusive` instead of `-x` and then `--unlock` instead of `-u` so it's explicitly clear.

**Comment by TMiguelT** [comment]
> I'm wondering - what would be the return code for the second worker that cannot create the lock? What in the above says "Try to make the lock, if it doesn't work, come back and try again (and do this until the container is available.)

This is the default behaviour of `flock`, I believe. My flock man page says:
> By default, if the lock cannot be immediately acquired, flock waits until the lock is available.

> Overall I think this is a really important thing to think about - aside from cluster resources, if you are pulling an image from a remote registry, that might have negative consequences for the registry.

My understanding of Singularity was that the actual *pulling* would be cached using the Singularity cache, and only the *building* would be duplicated. Is this not right? In any case, this will avoid smashing the Singularity cache at least.

> I also wouldn't be sparse with the variables, for some future user coming to read this, I would use --exclusive instead of -x and then --unlock instead of -u so it's explicitly clear.

Agreed! I'll edit the OP.

**Comment by vsoch** [comment]
> My understanding of Singularity was that the actual pulling would be cached using the Singularity cache, and only the building would be duplicated. Is this not right? In any case, this will avoid smashing the Singularity cache at least.

I think that if it's the case that the (finished image) isn't in the cache, all of the workers would start building (and then not copy to the final thing given that another worker got there first). It's been a while, so it might be good to check with others on slack.

**Comment by illusional** [comment]
That’s what the `[ ! -f $IMAGE ]` is for, once the next thread has the lock, this block finds the image exists and skips the pull.

**Comment by TMiguelT** [comment]
I think I misunderstood how to use `flock` in a bash script, so I've updated this with a tentative improvement:

```
            (
                flock --exclusive 200
                # Build the image
                if [ ! -f $IMAGE ]; then
                    singularity pull $IMAGE docker://${docker}
                fi
            ) 200>/var/lock/$IMAGE
```

**Comment by rherban** [comment]
Wouldn't you want to check if the image doesn't exist before locking?  
```
if [ ! -f $IMAGE ] ; then
  flock --exclusive 200
  if [ ! -f $IMAGE ]; then
    singularity pull $IMAGE docker://${docker}
```

Otherwise you're creating/checking file locks at every run, rather than only when the image doesn't exist?  Probably still want the inner IF so the subsequent locks don't have to run.

**Comment by TMiguelT** [comment]
Ah yes that makes sense. Since all the workers are run simultaneously (or close to it), I expect that most nodes will enter that first conditional, but it might be worth adding it just in case.

**Comment by TMiguelT** [comment]
For future reference, the discussion on Singularity slack is here: https://singularity-container.slack.com/archives/C0YKGK6D6/p1562648443118400

**Comment by miguelcarcamov** [comment]
Hi all, 
Can you please invite me to the slack workspace to see the discussion?

Regards

**Comment by TMiguelT** [comment]
I don't have the power to invite people, but the signup link is here: https://sylabs.io/singularity/slack/

**Comment by TMiguelT** [comment]
Also I've done some more research on `flock`, and although people claim that `flock` doesn't work on certain filesystems (NFS, for example), this has been fixed for a very long time in the Linux kernel (since Linux 2.6.12, released in 2005). In addition, it seems to be widely available in Linux distros, and is installed by default, unlike other locking tools like `lockfile`.

So I still think `flock` is the best option for this.

**Comment by vsoch** [comment]
Did you get to test this out @TMiguelT ?

**Comment by vsoch** [comment]
We could modify this for a general cluster submission script too, given a shared filesystem!

**Comment by TMiguelT** [comment]
I gather @illusional managed to do some testing. I haven't heard any details from him yet, though

**Comment by illusional** [comment]
Heya, I did manage to do some testing today (after some discussion with @TMiguelT as well).

Some small notes about my setup:

- I'm using Singularity that has the ability to store and run an OCI container to/from a file.
- I have one place `/path/to/containers/*` where I store all my containers.
- I transform the container digest (returned by Cromwell as `${docker}`) to generate a filename and use that to uniquely reference the container.

Notes about my (slightly modified) config below:

- My `$image` var has slashes in it (because it's a path to a file) which isn't correct, as `flock` expects a valid path, so I've just used `$docker_subbed` which is the transformed docker file.
- I didn't have write permission to `/var/lock/$imagename`, I've opted instead for the container directory.
- I wanted the output of `flock` to be redirected to Cromwell's `stderr.submit`.
- I do the second image check for when the lock is released, the locked processes will find the image and skip the pull (per @rherban's [comment](https://github.com/broadinstitute/cromwell/issues/5063#issuecomment-509677104))
```bash
# transformed docker digest
docker_subbed=$(sed -e 's/[^A-Za-z0-9._-]/_/g' <<< ${docker})
# output path of container (.sif)
image=/path/to/containers/$docker_subbed.sif
# declare a very similar path (.lock) where Cromwell can access
lockpath=/path/to/containers/$docker_subbed.lock 

if [ ! -f "$image" ]; then  # If we already have the image, skip everything
  (
  flock --verbose --exclusive 200 1>&2
  if [ ! -f "$image" ]; then   # do a second check once the lock has been released 
    singularity pull "$image" docker://${docker}
  fi
  ) 200>/var/lock/$lockpath
fi
```

Hope this helps!

**Comment by TMiguelT** [comment]
@illusional, would you mind posting your stderr files? What I'm interested in is the time it takes to acquire the lock for each worker, just to prove that it's working correctly.

**Comment by vsoch** [comment]
Would it be possible to use realistic paths, perhaps the `SINGULARITY_CACHEDIR`? And to make variables explicitly clear (and in quotes), maybe "${docker_subbed}.sif" instead of $docker_subbed.sif

The goal would be to have a general script that can work for most, correct?

**Comment by olsonanl** [comment]
Here is a slightly more general script (it assumes the lock file and saved image are in the current directory). It also does the pull into a temp file with a rename into the destination name at the end so that for a large image the -f check won't trigger for a partial download. I do some work here to deduce a filename that should match (as I understand the rules anyway) the one that the pull would create. I also include an option to force the path, since in my automation I tend to wish to define everything for my self. The derived or given image filename is echoed at the end.

YOUR_HOST is the name of the sregistry host (this is the context I'm doing this in).

```
#!/bin/bash                                                                                                                                  

lock_dir=.

if [[ $# -ne 1 && $# -ne 2 ]] ; then
        echo "Usage: $0 image-name [output-file]" 1>&2
        exit 1
fi
name=$1
output_file=$2

if [[ "$output_file" = "" ]] ; then

    # deduce filename                                                                                                                        

    output_file=`basename $name`
    if [[ $output_file =~ (.*):([^:]+)$ ]] ; then
        base=${BASH_REMATCH[1]}
        tag=${BASH_REMATCH[2]}
    else
        base=$output_file
        tag=latest
    fi
    output_file="${base}_$tag.sif"
fi

url=shub://YOUR_HOST/$name

# declare a very similar path (.lock) where Cromwell can access                                                                              
lock=$lock_dir/$output_file.lock
tmp=$output_file.tmp

if [ ! -f "$output_file" ]; then  # If we already have the image, skip everything                                                            
  (
  flock --exclusive 200
  if [ ! -f "$output_file" ]; then   # do a second check once the lock has been released                                                     
    singularity pull --nohttps $tmp $url
    mv $tmp $output_file
  fi
  ) 200>$lock
fi

rm -f $lock

echo $output_file
```

**Comment by vsoch** [comment]
I hope you are doing the pull on a login / dev node and not on something running massively in parallel? Or that the shub:// uri is interchangeable with docker:// or library:// ? Doing exec/run/pull in parallel is what led to devastating events in July that warranted adding extreme limits for all users to the server, and almost was the end of Singularity Hub. Ideally this really needs to be done with just one pull, and done before anything is run in parallel.

**Comment by olsonanl** [comment]
The context here is a small cluster with no shared filesystem, so the pulls are going onto local disks, from a local sregistry. Isn't it the case that the heavy lifting on the sregistry side is handled by nginx passing bits from disk to the net?

**Comment by olsonanl** [comment]
I had actually assumed that the singularity pull/caching mechanism would handle simultaneous downloads properly (by allowing only one to progress to fill the cache), but it doesn't appear to.

**Comment by vsoch** [comment]
Ah, if it's a local sregistry, then the build limits are not the same, and Singularity Hub isn't incurring any charges on Google Cloud :) 

Carry on!

Are you running a local sregistry? I put in a PR today to add a keystore, in case you want to test it out :)  https://github.com/singularityhub/sregistry/pull/235

**Comment by vsoch** [comment]
@olsonanl I think it depends on the version - I think(?) in newer versions a singularity hub image is cached, but (from actual experience) in _some_ version it's definitely not!

**Comment by olsonanl** [comment]
I was using 3.4.1 and saw behavior where one of the copies did the download into the cache, and the second saw the partial file in the cache and tried to run it and failed.

And yes, it's a local registry that I convinced to run inside singularity instead of docker since my production hosts are centos6 and are not happy with docker currently (and I'd rather have the control singularity gives me).

**Comment by vsoch** [comment]
Oh that's wicked! I haven't seen / heard of registries (being run with Singularity!) in the wild - did you use the same base and convert to Singularity recipes? Did you run as an instance, or run as instances with singularity-compose? Apologies for many questions, you've greatly peaked my interest! 

Interesting story - the _very first_ design for a Singularity Registry (I was doing back in 2016/early 2017) was totally based with Singularity - but because we didn't have instances proper yet, there were too many issues to make it feasible to develop (and I jumped to Docker). But now that we have those dependencies / instances, I could definitely look at it again.

The caveat (I suspect) is that we'd still need to run services with sudo - did you get around that?

**Comment by olsonanl** [comment]
I built a singularity image with a centos7 base and python3 & assorted requirements (based on your requirements.txt). I have nginx+upload built on the host, as well as redis and postgres. Checkout of the sregistry repo is on the host as well, and bound into the appropriate paths in the image. 

The main problems were making sure the upload paths agreed between nginx on the host and the registry in singularity, and losing the battle to use 'singularity instance' on centos6 and using 'singularity run' instead.  The nginx and postgres are running as root on the host, everything else as normal user.

**Comment by vsoch** [comment]
Ahh okay, so you did need root permission for what I expected. If you needed root for those 2, arguably another user (or cluster admin) doing the deployment would consider the additional root as trivial. And the benefits to this would be - having the registry deployed on a cluster (still needing root) but without Docker?

**Comment by olsonanl** [comment]
The main reason was that I don't have a native environment with python3 + the latest openssl that was usable with the github auth requirements.  I have python3 + openssl that I've built, but need xmlsec which segfaulted when I used the centos6 version with the hand-built python environment. I started down the path of building xmlsec which didn't immediately work properly so wanted to stop spiraling down the rathole of building chained dependencies.

**Comment by vsoch** [comment]
:rat: understood!

**Comment by olsonanl** [comment]
And yes, as an administrator of the local environment I see no reason not to use the local production services like database & nginx on the host.

**Comment by rhpvorderman** [comment]
I did not know of this thread.
At our institute we have solved this differently. We use `singularity exec` and no specific pull command. This will try to locate the image in the cache whis is located in `SINGULARITY_CACHEDIR` (env variable). If it is already there it will use it. If not, it will download it. This will lead to race condition if it is used in a scatter.

We use https://github.com/biowdl/prepull-singularity to pull the images beforehand, so no race conditions occur.
w
I am also thinking of adding a `docker_pull` thing to the config, so you can do `singularity exec {image} echo done!` or something similar to make sure the cache is populated at workflow initialization time. I have no ETA on this though, for now the prepull singularity script works.

**Comment by rhpvorderman** [comment]
And here is the config:
```hocon
            sbatch \
            --job-name="${job_name}" \
            --chdir="${cwd}" \
            --time="${time_minutes}" \
            --cpus-per-task="${cpu}" \
            --mem=$(echo "$MEMORY / 1024^2" | bc) \
            --output="${out}" \
            --error="${err}" \
            --wrap \
            'singularity exec --containall --bind /cluster-shared-filesystem,${cwd}:${docker_cwd} docker://${docker} sh ${script}
            rc=$?
            if [ ! -f ${cwd}/execution/rc ]
              then
                echo "$rc" > ${cwd}/execution/rc
            fi'
```

**Comment by rhpvorderman** [comment]
So I did some digging. The bad news: a `docker_pull` command will not work. It cannot be implemented at workflow initialization because at that point in time runtime attributes are not known. These are evaluated when the task is executed. This is due to inputs in WDL being dependent on the outputs of other tasks, which is what makes WDL great, so this cannot (easily) be fixed.

So a docker_pull command would have to be executed at task execution time. But then it is redundant. This command can be part of the submit script. 

Thanks @TMiguelT for suggesting flock. Together with `singularity exec` I think it can solve this particular use case. The `SINGULARITY_CACHEDIR` environment variable needs to be set to a location on the cluster. Then the following config can work:

```
    SLURM {
      actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"
      config {
        concurrent-job-limit = 200
        exit-code-timeout-seconds = 120
        # 4G Memory by default
        runtime-attributes= """
          Int cpu = 1
          Int? memory
          String? docker
          Int time_minutes = 120
        """
        submit-docker = """
            # Singularity pull image. 
            DOCKER_IMAGE="docker://${docker}"
            if [ -z $SINGULARITY_CACHEDIR ]; 
                then CACHE_DIR=$HOME/singularity/cache
                else CACHE_DIR=$SINGULARITY_CACHEDIR
            fi
            LOCK_DIR=$CACHE_DIR/flocks
            mkdir -p $LOCK_DIR
            LOCK_FILE=$LOCK_DIR/$(echo $DOCKER_IMAGE | md5sum | cut -d ' ' -f1)
            # flock should work as this is executed at the same node as cromwell.
            flock --verbose --exclusive --timeout 600 $LOCK_FILE singularity exec --containall $DOCKER_IMAGE exit 0

            # Partition selection
            PARTITION=all
            MEMORY=${default="4294967296" memory}
            if [ ${time_minutes} -lt 60 ]; then PARTITION=short; fi
            if [ $MEMORY -gt 107374182400 ] ; then PARTITION=highmem ; fi

            # Job submission
            sbatch \
            --partition=$PARTITION \
            --job-name="${job_name}" \
            --chdir="${cwd}" \
            --time="${time_minutes}" \
            --cpus-per-task="${cpu}" \
            --mem=$(echo "$MEMORY / 1024^2" | bc) \
            --output="${out}" \
            --error="${err}" \
            --wrap \
            'singularity exec --containall --bind /shared_cluster_dir,${cwd}:${docker_cwd} docker://${docker} sh ${script}
            rc=$?
            if [ ! -f ${cwd}/execution/rc ]
              then
                echo "$rc" > ${cwd}/execution/rc
            fi'
        """
        kill = "scancel ${job_id}"
        kill-docker = "scancel ${job_id}"
        check-alive = "squeue -j ${job_id}"
        job-id-regex = "Submitted batch job (\\d+).*"
```

**Comment by TMiguelT** [comment]
> So a docker_pull command would have to be executed at task execution time. But then it is redundant. This command can be part of the submit script.

I looked into this a while ago so I might be wrong, but I think a `docker_pull` hook would still be useful, even at runtime, because it would be run only once, and *not* scattered, unlike the actual `submit_docker` hook. This would give it time to pull/convert the container without any race condition issues, meaning we don't have to use `flock` or any of that messy bash.

The execution graph would look like:
```
          pull_docker
          ⭩    ↓    ⭨
    submit   submit   submit
```

**Comment by rhpvorderman** [comment]
BTW, I changed the config above because the only viable way to implement a lock in singularity is one lock per cache. If two images that are different but with shared layers are written to the cache, it can still become corrupted!

@TMiguelT This will be hard to pull of in the code because the runtime attributes are evaluated just before task submissions. Also there will still be race conditions. Only one process should pull to the same cache at the same time. This is because images have shared layers. Also this requires additional code and is only applicable to the singularity use cache. The few lines in the script are way way way less than any code that would be required to make this happen.

As regards tot he messy bash, no bash is required. Flock + the pull command is just one line. The only bash that is required is to set a few variables, but that is not really scripting.

 Flock is a great solution. Thanks a lot for suggesting it! The only better solution would have been that singularity has implemented such a filelock itself. As long as the pull process happens on the same node, the kernel will ensure that there are no race conditions. Of course this doesn't work on another node, so the flock command should be placed before the submit command.
