### ISSUE TITLE
obscure validation error: Expected rbrace after `input:` in call

### ISSUE THREAD

**Issue by DSLituiev** [broadinstitute/cromwell#5256]
I have a following pipeline which fails validation, and I cannot see what can be wrong with it:

```
version 1.0

## 
# Git URL import
import "https://raw.githubusercontent.com/DSLituiev/five-dollar-genome-analysis-pipeline/master/tasks/to_uBam.wdl" as touBam

# WORKFLOW DEFINITION
workflow WGUnMap {
  input {
    File mapped_bam
    String bam_base
  }

  call touBam.unMap {
    input:
      File mapped_bam=mapped_bam,
      String unmapped_base=bam_base
  }

  # Outputs that will be retained when execution is complete
  output {
    File unmapped_bam = touBam.out
  }
}
```

The error is:
```
java -jar `which womtool.jar` validate  unmap.wdl
ERROR: Unexpected symbol (line 46, col 7) when parsing '_gen19'.

Expected rbrace, got "File".

      File mapped_bam=mapped_bam,
      ^

$call_body = :input :colon $_gen19 -> CallBody( inputs=$2 )
```

Any ideas? Why brace is expected to be closed right after the colon?

**Comment by aednichols** [comment]
Hi @DSLituiev, thanks for your question and welcome to our repo!

I think I know the problem – the inputs in a call do not need the type declarations (like `File` and `String`). Give this a try:
```
 call touBam.unMap {
    input:
      File mapped_bam=mapped_bam,
      String unmapped_base=bam_base
  }
```
Unfortunately the error is pretty confusing because when a workflow doesn't conform to the grammar, the parser has a very hard time describing what's wrong in meaningful terms (it just kind of freaks out).

**Comment by lihaicheng7003** [comment]
I encountered the same problem and was frustrated, this method didn't work. Finally, I realized that I needed to add a version number at the beginning of the WDL script, like "version 1.0".
