### ISSUE TITLE
SQlite

### ISSUE THREAD

**Issue by ParkvilleData** [broadinstitute/cromwell#5271]
Hi,

Is it possible to use an SQLite database instead of a MySQL server to allow for call-caching?

This post comes close to saying there isn't a way without a lot of work (https://github.com/broadinstitute/cromwell/issues/3786). Is this still the position?

I know you can use a MySQL database, but sometimes the extra resources are not available or difficult to get. An option for a local persistence database would be very useful.

Thanks for your help,

**Comment by aednichols** [comment]
Hello and thanks for your question. We do not have any current plans to support SQLite (though I personally think it's a fantastic product!).

If you can help us understand the scenario in which you're running Cromwell we may be able to offer some advice. In particular, it's surprising that a MySQL database is "not available or difficult to get"; the typical scenario we envision for running Cromwell with persistence is a Cromwell Docker plus a MySQL Docker.

**Comment by rhpvorderman** [comment]
This is also something we would want for our cluster. Users are not allowed to run docker containers on our HPC (that would give them root access :scream:). So we use cromwell on the command line instead. We modified our cromwell configuration to run with singularity containers instead of docker containers.

Setting up a MySQL server somewhere is not easy for the average user. Furthermore we used to set up a MySQL server for all users on the cluster, but that meant they had to share a database user and password (they were all using the same configuration). This caused a lot of issues. 

Mostly cromwell is run project based. So the call-caching is only interesting for that particular project. Also using a file-based database will automatically ensure that only people with rights to the share the project is on will have access. This is also of importance in a shared cluster environment.

At LUMC we currently implement this by using the HSQLDB in-memory database with a persistence file. This has some disadvantages:
1. Cromwell needs more memory compared to using a MySQL server
2. The HSQLDB persistence files are huge, badly compressed (when compression is used). 3 GB is normal. Tarring and zipping will get this down to under <50 mb... 
3. It is slower than using a MySQL server.

I think that SQLite will solve problem 1 and 2. (3 is inherent to using a file-based DB). 

Having a database is better than to have nothing at all, which is why many users are pining for SQLite. When looking into it I found the option for the persistence file. Although SQLite will be much better, this does not require any extra effort from the Cromwell developers and can already help out a lot of users. I will document how we did this in the Cromwell documentation so everyone can use this.

**Comment by ParkvilleData** [comment]
@aednichols 

Thanks for your response. We're in a University and the sys admins are worried that with users submitting thousands of jobs, depending on what cromwell actually sends MySQL there may be quite a bit of overhead. Do you have a link to what Cromwell stores in the MySQL database? That may assuage some of their concerns. Using SQLite would just be easier, users can create a local instance and be on with it.

@rhpvorderman 

That sounds like a workable option. That sounds exactly like our situation, it would be great if you could keep us updated! We would definitely be very useful for us!

Thanks,
Bobbie.

**Comment by rhpvorderman** [comment]
@ParkvilleData It is now in the development docs. https://cromwell.readthedocs.io/en/develop/Configuring/#database

The formatting is a bit off, but that will be fixed. It should be in the stable docs (the default cromwell.readthedocs.io) from version 48 onwards.

**Comment by illusional** [comment]
Hey @ParkvilleData, I PM'd you but thought I'd leave a comment here. It's possible to run MySQL / MariaDB inside of a container. You have to do some small tweaking for Singularity, but it's possible to automate this.

https://github.com/PMCC-BioinformaticsCore/janis-assistant/blob/master/janis_assistant/management/mysql.py

This uses this Python class to interact with Singularity: https://github.com/PMCC-BioinformaticsCore/janis-assistant/blob/master/janis_assistant/containers/singularity.py

**Comment by Alexander-Stuckey** [comment]
I just want to ask, is using the local file-based database only supported for call caching from version 48 onwards?
I'm running both cromwell 43 and 47, both versions appear to use the file-based database fine for running a workflow, but 43 does not seem to use it for call caching (haven't tested with 47 yet).

**Comment by DavyCats** [comment]
@Alexander-Stuckey We are using the file-based database with cromwell 46.1 and the call-caching is working just fine.

**Comment by Alexander-Stuckey** [comment]
@DavyCats Perfect, just what I wanted to hear thanks :)

**Comment by illusional** [comment]
Hi, I've been running Cromwell with the file-based DB fine for a few weeks, but today had a seemingly unrelated problem and this seems to have corrupted the DB.

Potentially unrelated error:
```
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://cromwell-system/user/cromwell-service/WorkflowStoreCoo
rdinatedAccessActor#1289452983]] after [60000 ms]. Message of type [cromwell.engine.workflow.workflowstore.WorkflowStor
eCoordinatedAccessActor$FetchStartableWorkflows]. A typical reason for `AskTimeoutException` is that the recipient acto
r didn't send a reply.
        at akka.pattern.PromiseActorRef$.$anonfun$defaultOnTimeout$1(AskSupport.scala:675)
        at akka.pattern.PromiseActorRef$.$anonfun$apply$1(AskSupport.scala:696)
        at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:202)
        at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
        at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:113)
        at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
        at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
        at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:334)
        at akka.actor.LightArrayRevolverScheduler$$anon$3.executeBucket$1(LightArrayRevolverScheduler.scala:285)
        at akka.actor.LightArrayRevolverScheduler$$anon$3.nextTick(LightArrayRevolverScheduler.scala:289)
        at akka.actor.LightArrayRevolverScheduler$$anon$3.run(LightArrayRevolverScheduler.scala:241)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

Error that I receive now when I try to start Cromwell:

```
2020-05-05 15:31:33,773  INFO  - dataFileCache commit start
2020-05-05 15:33:32,400  ERROR - Failed to instantiate Cromwell System. Shutting down Cromwell.
java.sql.SQLTransientConnectionException: db - Connection is not available, request timed out after 121641ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
        at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
        at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:494)
        at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
        at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
        at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:250)
        at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:249)
        at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
        at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:275)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

Does anyone have any advice for repairing the db, or working out more what's happened?

**Comment by rhpvorderman** [comment]
Your DB has become too big. This means it will take too much time to open the database and you will get connection timeouts. (These files can be multiple GBs).

Here is our database setup:
```
database {
  profile = "slick.jdbc.HsqldbProfile$"
  db {
    driver = "org.hsqldb.jdbcDriver"
    # See http://hsqldb.org/doc/2.0/guide/dbproperties-chapt.html
    # Shutdown=false. Cromwell will shutdown the database
    # hsqlldb.default_table_type=cached. By default hsqldb uses in memory tables. 
    # Setting this to cache for improved memory usage.
    # hsqldb.result_max_memory_rows=10000 . Limits the amount of rows in memory for temp tables
    # hsqldb.tx=mvcc cromwell default. Not changing it. Not clear what this does. http://hsqldb.org/doc/guide/sessions-chapt.html#snc_tx_mvcc
    # hsqldb.large_data=true. Cromwell creates huge DBs that need to be opened.
    # hsqldb.applog=1. Log errors.
    # hsqldb.lob_compressed=true. Compress lobs. This saves a lot of space.
    # hsqldb.script_format=3. Compress script. (uses gzip internally).
    url = """
    jdbc:hsqldb:file:cromwell-executions/cromwell-db/cromwell-db;
    shutdown=false;
    hsqldb.default_table_type=cached;hsqldb.tx=mvcc;
    hsqldb.result_max_memory_rows=10000;
    hsqldb.large_data=true;
    hsqldb.applog=1;
    hsqldb.lob_compressed=true;
    hsqldb.script_format=3
    """
    # Override the cromwell default of only 3 seconds (3000 milliseconds) and allow for 300s to read the database file.
    connectionTimeout = 300000
    numThreads = 1
   }
}
```
Please note the `connectionTimeout = 300000` where we set the connection timeout to 5 minutes. This works for most cases.

On a side note: HSQLDB has got to be the worst performing embedded database designed in the history of mankind. When running a decent-sized WDL workflow it can get 30 GB in memory! When using the file-based database it still needs 2 GB in memory (on top of the 1 GB that cromwell needs) is very slow, and creates a multiple GB file database. 
MySQL performs much better with cromwell, but is infeasible to use in a per-project, per-user fashion.

[I am working on solving the problem using SQLite](https://github.com/broadinstitute/cromwell/issues/5490) but there is NO ETA, and I don't know if I will ever get it to work. Still it is worth trying.

**Comment by illusional** [comment]
Hey @rhpvorderman, that worked great for a bit so thanks for the comment! 

I sometimes seem to be getting timeouts on smaller databases (300 seconds for a 2GB file), I think this might be due to Cromwell terminating incorrectly and it not starting up again. I'm following the SQLite with fingers crossed, and if there's anything I can do I'm more than happy to help.

**Comment by rhpvorderman** [comment]
> I sometimes seem to be getting timeouts on smaller databases (300 seconds for a 2GB file), I think this might be due to Cromwell terminating incorrectly and it not starting up again.

If the database is on NFS it might not be cached locally. And with a 100mbit connection it might happen. But this is just speculation.

Anyway, I hope my PR on liquibase gets merged soon so I can continue working on the problem.

**Comment by aednichols** [comment]
> We do not have any current plans to support SQLite

>  I personally think it's a fantastic product!

These statements are both as true today as 4 years ago, gonna close this issue so as not to overpromise/mislead.

**Comment by rhpvorderman** [comment]
To add to this, a working implementation with SQLite was already developed, but it turns out cromwell communicates with the database often. Since SQLite is filebased, this would lead to significant slowdowns. The HSQL in-memory database with overflow file, while generating much larger files, was also much quicker.
