### ISSUE TITLE
ValidationActor returns WorkflowDescriptor

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#569]

**Comment by gauravs90** [comment]
Please hold on to this thought! I think the responsibility of that shouldn't lie with the ValidateActor!

**Comment by gauravs90** [comment]
That;s multiple responsibilities within one single entity

**Comment by geoffjentry** [comment]
I'd agree with that. I've always felt that the VA should only return a yes/no, although perhaps my issue is being overly pedantic with the name of the actor.

The argument for this though was that because people (including yourself, IIRC) didn't want to receive the simple yes/no and thus replicate the parsing of the input files the VA was handing back the parsed components. Once the validation is taken out of WorkflowDescriptor's apply() method it becomes a simple case class constructed by those same values so the effect is the same.

**Comment by gauravs90** [comment]
This should be closed?

**Comment by cjllanwarne** [comment]
Closed as duplicate
