### ISSUE TITLE
the parameter of '--imports' can not be directory that includes 'WDL' files, must be zip compressed file?

### ISSUE THREAD

**Issue by 1156054203** [broadinstitute/cromwell#5693]
###
###
###
###

**Comment by illusional** [comment]
The parameter `-p` --imports` is a:

```
  -p, --imports <value>    A directory or zipfile to search for workflow imports.
```

Same as in the REST API description: https://cromwell.readthedocs.io/en/gs_ba_6078/api/RESTAPI/#parameters

**Comment by aednichols** [comment]
Hi @1156054203, I took a look at the Cromwell codebase and it looks possible that only ZIP files work with the `--imports` flag, not directories. This would be a bug relative to the documentation.

Can you confirm this is what you're seeing?

**Comment by 1156054203** [comment]
Hi,
&nbsp; &nbsp;Thank you for your reply. The screenshot below is the output of the software help command I ran, and I was misled by the statement marked in the red box.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "broadinstitute/cromwell"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月10日(星期一) 晚上11:05
收件人:&nbsp;"broadinstitute/cromwell"<cromwell@noreply.github.com&gt;;
抄送:&nbsp;"夜角纷飞"<1156054203@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [broadinstitute/cromwell] the parameter of '--imports' can not be directory that includes 'WDL' files, must be zip compressed file? (#5693)





 
Hi @1156054203, I took a look at the Cromwell codebase and it looks possible that only ZIP files work with the --imports flag, not directories. This would be a bug relative to the documentation.
 
Can you confirm this is what you're seeing?

**Comment by 1156054203** [comment]
Thank you for your&nbsp;reply.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "broadinstitute/cromwell"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月10日(星期一) 上午7:56
收件人:&nbsp;"broadinstitute/cromwell"<cromwell@noreply.github.com&gt;;
抄送:&nbsp;"夜角纷飞"<1156054203@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [broadinstitute/cromwell] the parameter of '--imports' can not be directory that includes 'WDL' files, must be zip compressed file? (#5693)





 
The parameter -p --imports` is a:
   -p, --imports <value&gt;    A directory or zipfile to search for workflow imports.  
Same as in the REST API description: https://cromwell.readthedocs.io/en/gs_ba_6078/api/RESTAPI/#parameters

**Comment by aednichols** [comment]
Developer notes:

When first launching single workflow mode, Cromwell calls `cromwell.CommandLineArguments#validateSubmission` and generates a `cromwell.CommandLineArguments.ValidSubmission` if the submission looks good. `ValidSubmission` has the appearance of supporting directories because it has the member `dependencies`.

In [both](https://github.com/broadinstitute/cromwell/blob/9249537fd094c6979b0c64e99fcc90d48c861487/server/src/main/scala/cromwell/CromwellEntryPoint.scala#L229) [places](https://github.com/broadinstitute/cromwell/blob/9249537fd094c6979b0c64e99fcc90d48c861487/server/src/main/scala/cromwell/CromwellEntryPoint.scala#L249) where `validateSubmission` is actually called, however, we copy the value into another variable that is named & treated as the path to a zip file.
