### ISSUE TITLE
Simplify FinalCalls to functions, instead of tracking in ExecutionStore

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#579]
Can get rid of distinct BackendCall / FinallCall, there can be only kind of `JobDescriptor`.

**Comment by Horneth** [comment]
Does this min refactoring Final Calls to run on a backend instead of in the engine ?

**Comment by Horneth** [comment]
Mean*

**Comment by mcovarr** [comment]
Yes that's what it means.

**Comment by kshakir** [comment]
The existing #694 tries to get rid of FinalCallJobDescriptors, but ends up copying files still in process instead of on a backend. Once the ShadowWorkflowActor work is complete, we will revisit the concept of removing the FinalCallJobDescriptor, leaving only the BackendCallJobDescriptor. Instead of merging the two, we will remove the FinalCallJobDescriptor and run the existing Final Call copies in process but without individual tracking.

More notes in this [google doc](https://docs.google.com/document/d/1Zix2NEHVfdzXH5GPm013OtshzmfIlCsmfr-cUZ1e-gc/edit).

**Comment by ruchim** [comment]
Spoke to Khalid, making a replacement ticket to avoid confusion.
