### ISSUE TITLE
Support 'Fail Fast'

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#587]
In cases where call caching is not being used (as is the case for Genomes On the Cloud for the time being), the ability to have workflows "fail fast" is desired.  Fail fast in this case mean, once a task has failed no new tasks should be started (currently running tasks can finish) and then the workflow should be set to failed.

This is important because when running a workflow, and you can't reuse the non-failed work, you want to know the workflow will fail as soon as possible.  With a long running workflow, an early failure with few downstream dependencies you have to wait a long time (24 hours for GOTC) to realize it's actually failed.

This should be specifyable as a workflow option, e.g. failure-strategy = fast where the current behavior is 'slow'.  If it's easy to also have this as a server config setting for the default that would be a nice to have but not critical.

**Comment by mcovarr** [comment]
To be clear, fail-fast should not attempt to abort currently running calls even if those calls might otherwise continue to run for a long time?

**Comment by kcibul** [comment]
Yes that is correct.  A future feature could be "fail immediate" which would terminate running jobs, but that isn't this one

**Comment by mcovarr** [comment]
Sounds good

**Comment by jsotobroad** [comment]
I believe we want to patch this off of the cromwell hash we are currently
using - 3eb1623
<https://github.com/broadinstitute/cromwell/commit/3eb1623d9a5ffdf0fc3626820eab84ae6560b2cd>

**Comment by mcovarr** [comment]
Hey @jsotobroad sorry if this is a well-known issue but I've been OOO for a couple of days, but why would these changes be made relative to a particular hash and not off develop?

**Comment by Horneth** [comment]
@mcovarr We though develop is in a relative unstable state with all the restructuring going on and that it would be safer to branch off of an earlier version. This commit is the commit that fixed the duplicate inputs bug.

**Comment by mcovarr** [comment]
Is there a specific instability we're concerned about?  Otherwise I thought one of the advantages of doing the PBE restructuring against develop was to get our changes out and battle-tested as we go along.  Interested to hear from @kcibul and @geoffjentry on this point.

**Comment by kcibul** [comment]
If the cromwell team feels like develop is as stable as it was a few weeks
back, I'd support using it.  Thibault raised a concern that this might not
be the case.

-------------------------------
Kristian Cibulskis
Chief Architect, Data Sciences & Data Engineering
Broad Institute of MIT and Harvard
kcibul@broadinstitute.org

**Comment by mcovarr** [comment]
I have no reason to believe develop is any less stable today than it was a few weeks ago, but if anyone feels otherwise please speak up! 

Branching GotC releases from a branch based at this hash means we'll need to put fixes on both the GotC branch and develop going forward.  That will become increasingly difficult as these branches diverge.  And eventually PBE Cromwell would be released with the full bolus of ported fixes that were never previously tested at scale.

**Comment by geoffjentry** [comment]
:+1: to what @mcovarr said. Every merge into develop is run against the same tests/tyburn as any other thing so the fact that it involves backends shouldn't matter. Further, doing it this way gives us better insight as we move along.

**Comment by cjllanwarne** [comment]
Well yeah but it has things like per-WF backends...

**Comment by geoffjentry** [comment]
@cjllanwarne Which would always be set to JES for their case

**Comment by Horneth** [comment]
It just feels to me that we're adding a lot of "temporary features" - "step towards PBE that are going to disappear with the next PR", TODOs like "this is awful but will be better soon", and I'm not 100% confident that all of these are getting fully tested (which makes sense because we know they're temporary anyway).
As far as I understand GotC are trying to have 200 running smoothly and having them alpha-test our PBE WIP may not be the best way to do that.

**Comment by mcovarr** [comment]
If we think what we're doing is that bad I don't think it should go to develop.  We could branch develop to hold back a logical grouping of WIP until it stabilizes, and once it does stabilize then merge it to develop.
