### ISSUE TITLE
Allocate more vCPUs than specified in WDL file

### ISSUE THREAD

**Issue by anniepgu** [broadinstitute/cromwell#6216]
###
###
###
###

Cromwell version is 55
We had submitted workflow pipelines on GCP PAPIv2 (https://genomics.googleapis.com/), in WDL file, set cpu: "4", memory: "48 GB", the actual VM  created as custom (8 vCPUs, 48 GB memory), for "memory": "64 GB" "cpu": "8", the actual VM created as (10 vCPU, 64 GB), Cromwell did not created VM as configured in WDL

Thanks

**Comment by aednichols** [comment]
Cromwell submits the VM size exactly as specified by the user. GCP alters the machine size on your behalf to comply with the minimum and maximum ratio of vCPUs to memory gigabytes.

For example, the 4 vCPU / 40 GB machine is non-compliant because 4 CPUs support up to 4 x 6.5 = 26 gigabytes of memory. So it adds CPUs to give you the memory you want.

For more information, see https://cloud.google.com/compute/docs/instances/creating-instance-with-custom-machine-type#specifications
