### ISSUE TITLE
sep has no effect outside command block

### ISSUE THREAD

**Issue by TedBrookings** [broadinstitute/cromwell#6789]
When invoked inside the command block `~{sep="_" my_arr}` works as expected. But outside the command block, it has no affect. e.g.
```
task MyTask {
    input {
        Array[String] my_arr = ["foo", "bar"]
    }

    String bad_str = "~{sep='_' my_arr}" # bad_str = '["foo", "bar"]'
    command <<<
        GOOD_STR="~{sep='_' my_arr}" # GOOD_STR = "foo_bar"
    >>>
```
I'm encountering this problem using the methods cromwell, running version 77. The WDL is version 1.0. I've made no effort to alter the backend in the workflow options, so I assume it's Google PAPI v2.

**Comment by aednichols** [comment]
I wasn't sure about this so I looked it up in the [spec](https://github.com/openwdl/wdl/blob/main/versions/1.0/SPEC.md#sep).

The outline seems to suggest that `sep` is specifically a command block feature, it's not mentioned elsewhere. Hope this helps.

<img width="325" alt="Screen Shot 2022-06-30 at 4 59 20 PM" src="https://user-images.githubusercontent.com/1087943/176777649-c78e42f4-4fa5-4df0-a119-78facf2bbbe5.png">

**Comment by pshapiro4broad** [comment]
It seems like the bug here is that cromwell accepts `sep` at all in this context, since it doesn't support it. Given the way the 1.0 WDL spec was created, I'm not sure if the current behavior is intentional or not -- there doesn't seem to be a reason why `sep` wouldn't be supported in any String Interpolation context.

If you test this out with `miniwdl`, it says that `sep` is invalid outside of a command block in WDL 1.0. In WDL 1.1, it's supported in both contexts (using the new style `sep` operator), and miniwdl allows it.

In any event, changing cromwell's behavior for WDL 1.0 doesn't seem likely at this point, so I think the best way forward is to add WDL 1.1 support to cromwell, which supports this and many other features.

**Comment by aednichols** [comment]
That's true, from reading

>outside the command block, it has no affect

it does seem that it's an inadvertent no-op rather than an error. Good take!
