### ISSUE TITLE
Simplify FinalCalls to functions, instead of tracking in ExecutionStore

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#773]
Find a way to perform FinalCalls as functions with a WorkflowActor State 

WorkflowActor uses some state to run various final file copies: 
- Possibly use the existing Finalizing state
- Possibly create another state that means the workflow is in this phase of running this specific group operations

If the process dies during this state, upon restart, the workflow would retry copying all of the files, meaning the final actions: 
- Do not need to be a CallKey or other JobKey/ExecutionStoreKey
- Do not need to be tracked in the WorkflowActor ExecutionStore
- Do not need to be individually tracked with state in the database’s Execution table
- Will possibly use more IO than strictly necessary on restart, as we don’t know what copies succeeded and what failed

**Comment by ruchim** [comment]
More details in the doc: https://docs.google.com/document/d/1Zix2NEHVfdzXH5GPm013OtshzmfIlCsmfr-cUZ1e-gc/edit 
Under "Future Proposal" section.

**Comment by scottfrazer** [comment]
From discussion yesterday it seems that this needs the metadata service to be implemented.  There are three kinds of final calls:

* Copy workflow logs - this only needs access to filesystems in the engine.  Log location is specified in the workflow options
* Copy workflow outputs - this needs filesystem access in the engine.  Takes a sub-set of the call outputs and copies them.
* Copy call logs - Call logs can be different for each backend, and since this information is now being stored in the metadata service, we need some convention for which keys are valid call-log keys.
